rancher/webhook

pkg/generated/controllers/management.cattle.io/factory.go, pkg/generated/controllers/management.cattle.io/interface.go, pkg/generated/controllers/management.cattle.io/v3/cluster.go, pkg/generated/controllers/management.cattle.io/v3/globalrole.go, pkg/generated/controllers/management.cattle.io/v3/interface.go, pkg/generated/controllers/management.cattle.io/v3/roletemplate.go
Related issue:
https://github.com/rancher/rancher/issues/31974
=> Update copyright via go generate

charts/rancher-webhook/templates/deployment.yaml, charts/rancher-webhook/values.yaml
=> Fix issue #23

pkg/auth/escalation.go, pkg/resources/roletemplate/roletemplate.go
Issue: 
- https://github.com/rancher/rancher/issues/33278
=> RoleTemplate Validation - Disallow empty verbs

pkg/auth/escalation.go, pkg/resources/roletemplate/roletemplate.go
Issue: 
- https://github.com/rancher/rancher/issues/33286
=> [Backport] Disallow empty verbs for RoleTemplates

pkg/resources/globalrole/globalrole.go, pkg/server/server.go, pkg/server/validation.go
Issue: 
- https://github.com/rancher/rancher/issues/33286
=> [release/v0.1] Add validation logic around GlobalRole resources

pkg/resources/globalrole/globalrole.go, pkg/server/server.go, pkg/server/validation.go
Issue:
- https://github.com/rancher/rancher/issues/33278
=> Forwardport GlobalRole validation logic

pkg/resources/globalrole/globalrole.go, pkg/resources/roletemplate/roletemplate.go
Issue:
- https://github.com/rancher/rancher/issues/33286
=> Handle pre-delete updates that remove finalizers

go.mod, go.sum, main.go, pkg/resources/validation/globalrole/globalrole.go, pkg/resources/validation/globalrolebinding/globarolebinding.go, pkg/resources/validation/roletemplate/roletemplate.go
Previous PRs:
- https://github.com/rancher/webhook/pull/37
- https://github.com/rancher/webhook/pull/33
=> [Forwardport] Add debug logging and fix GRB deletion

pkg/resources/mutation/secret/secret.go, pkg/server/mutation.go, pkg/server/server.go
https://github.com/rancher/rancher/issues/32414
=> Add creatorID anno to secrets on create

charts/rancher-webhook/templates/pre-delete-hook-cluster-role.yaml, charts/rancher-webhook/templates/pre-delete-hook-job.yaml, charts/rancher-webhook/templates/pre-delete-hook-psp.yaml
issue https://github.com/rancher/rancher/issues/34188
a corresponding PR in rancher/rancher: https://github.com/rancher/rancher/pull/34286
Note:
This PR is already tested in a hardened cluster
TODO:
=> add support for running in the hardened cluster

scripts/package-helm
Issue: 
The package-helm script replaces all tag values in the values.yaml 
Fix:
Update the regex to match "tag: latest" only 
Related PR: https://github.com/rancher/charts/pull/1418
=> Fix package-helm script

charts/rancher-webhook/templates/_helpers.tpl, charts/rancher-webhook/templates/pre-delete-hook-cluster-role-binding.yaml, charts/rancher-webhook/templates/pre-delete-hook-cluster-role.yaml, charts/rancher-webhook/templates/pre-delete-hook-job.yaml, charts/rancher-webhook/templates/pre-delete-hook-psp.yaml, charts/rancher-webhook/templates/pre-delete-hook-service-account.yaml, charts/rancher-webhook/values.yaml, scripts/package-helm
New Issue | Original PR | Description | Supporting PR
------ | --------------- | ----------- | ------
https://github.com/rancher/rancher/issues/34453 | https://github.com/rancher/webhook/pull/45, https://github.com/rancher/webhook/pull/47 | delete the `mutatingwebhookconfigurations` when uninstalling the app |
https://github.com/rancher/rancher/issues/34320 | https://github.com/rancher/webhook/pull/46, https://github.com/rancher/webhook/pull/51 | support hardend cluster |  https://github.com/rancher/rancher/pull/34465
TODO after merging :
=> [release/v0.1] backport multiple fixes

charts/rancher-webhook/templates/pre-delete-hook-job.yaml
Forward ports https://github.com/rancher/webhook/pull/71
Related Issue: https://github.com/rancher/rancher/issues/33724
(cherry picked from commit d23b74f44c6556fbbcec231a8a3b1c0decf5b125)
=> [master] Run pre-delete-hook-job as root

pkg/auth/escalation.go, pkg/resources/globalrole/globalrole.go, pkg/server/validation.go
=> Adding GR check

charts/rancher-webhook/values.yaml
This version supports s390x arch.
=> Upgrade kubectl version to v1.23.3

.drone.yml, Dockerfile.dapper, package/Dockerfile
Move base image to SLE BCI and run as non-privileged user.
Signed-off-by: Guilherme Macedo <guilherme.macedo@suse.com>
=> Move base image to SLE BCI and run as non-privileged user

.github/dependabot.yml
Updates https://github.com/rancher/webhook/pull/86
=> Fix dependabot.yml syntax error

pkg/server/server.go
Issue: https://github.com/rancher/rancher/issues/38845
=> Fix HTTPS Port

charts/rancher-webhook/templates/deployment.yaml, charts/rancher-webhook/templates/pre-delete-hook-job.yaml, charts/rancher-webhook/values.yaml
Adds the ability for users to set the priorityClassName of rancher-webhook via helm values.
=> Adds priorityClassName to the webhook deployment.

pkg/resources/validation/projectroletemplatebinding/projectrtb.go, pkg/resources/validation/projectroletemplatebinding/projectrtb_test.go
Adds ProjectName check to PRTB validation.
=> Adds ProjectName validation to PRTB.

.drone.yml, Dockerfile.dapper, go.mod, go.sum, pkg/health/health.go, pkg/server/server.go, scripts/integration-test, scripts/package, scripts/test, tests/integration/clusterRoleTemplataeBinding_test.go, tests/integration/feature_test.go, tests/integration/globalRole_test.go, tests/integration/golbalRoleBinding_test.go, tests/integration/main_test.go, tests/integration/mgmtCluster_test.go, tests/integration/projectRoleTemplateBinding_test.go, tests/integration/provCluster_test.go, tests/integration/rkeMachineConfig_test.go, tests/integration/roleTemplate_test.go, tests/integration/secret_test.go
This adds integration tests to our webhook.
Test steps
1. Build integration test binary and the rancher-webhook Docker image
2. Save the newly created docker image into `dist/artifacts`
3. Start a Rancher & k8s instance with the latest released rancher image.
4. Import the newly created rancher-webhook image into k8's containerd registry
5. Update the rancher webhook deployment to use the new rancher-webhook image.
6. Run the integration test.
=> Integration test

charts/rancher-webhook/charts/capi/templates/service.yaml, charts/rancher-webhook/templates/service.yaml, pkg/codegen/main.go, pkg/generated/objects/core/v1/objects.go, pkg/resources/validation/namespace/namespace.go, pkg/resources/validation/namespace/namespace_test.go, pkg/resources/validation/psa-validation.go, pkg/server/handlers.go, tests/integration/main_test.go, tests/integration/namespace_test.go
Note, currently based on PR #150, will rebase once that merges
=> Add webhooks to namespaces and projects for editing PSA labels

charts/rancher-webhook/Chart.yaml
https://github.com/rancher/rancher/issues/39854
=> Bump kube-version to support k8s 1.25

pkg/resources/validation/namespace/namespace_test.go, pkg/resources/validation/psa-validation.go
Addresses issue found in testing of https://github.com/rancher/rancher/issues/38701
Updated handling of potential PSA-related label deletion.
Tweaked 1 test and added 2 new unit tests to cover the behaviors.
=> Fix handling of PSA label deletion

charts/rancher-webhook/templates/pre-delete-hook-cluster-role.yaml, charts/rancher-webhook/templates/pre-delete-hook-psp.yaml, charts/rancher-webhook/templates/validate-psp-install.yaml, charts/rancher-webhook/values.yaml
https://github.com/rancher/rancher/issues/40326
=> Add PSP references along with setting and logic to handle PSPs

charts/rancher-webhook/templates/validate-psp-install.yaml
As updated in:  https://github.com/rancher/rancher/issues/40326
=> Update check for PSP capabilities

go.mod, go.sum
https://github.com/rancher/rancher/issues/40609
Need to update apis before https://github.com/rancher/rancher/pull/40730 will pass.
=> Update rancher apis

pkg/resources/mutation/cluster/provisioningcluster.go, pkg/resources/mutation/cluster/provisioningcluster_test.go
https://github.com/rancher/rancher/issues/40826
Every time we update the provisioning cluster struct definition we are going to have to update the webhook's pkg/apis module dependency (like we did for https://github.com/rancher/webhook/pull/193) including for testing locally, which is probably going to result in a lot of churn for team 2 as we develop, and team 1 for merging webhook PRs and cutting releases. This changes the current behavior to only create a patch based on the marshalled json to prevent dropping fields unintentionally. I tested this locally, and it's now working as expected (I can add fields to the provisioning cluster without having to do a release of the webhook).
=> Marshal before patching

charts/rancher-webhook/templates/deployment.yaml
=> Update webhook service to use correct tls secret

charts/rancher-webhook/Chart.yaml
Issue: https://github.com/rancher/rancher/issues/41509
=> Bump supported K8s version to 1.26

README.md, docs.md, pkg/codegen/docs.go, pkg/resources/core/v1/namespace/Namespace.md, pkg/resources/core/v1/secret/Secret.md, pkg/resources/core/v1/secret/mutator.go, pkg/resources/core/v1/secret/mutator_test.go, pkg/resources/core/v1/secret/validator.go, pkg/resources/management.cattle.io/v3/clusterroletemplatebinding/ClusterRoleTemplateBinding.md, pkg/resources/management.cattle.io/v3/feature/Feature.md, pkg/resources/management.cattle.io/v3/feature/validator.go, pkg/resources/management.cattle.io/v3/feature/validator_test.go, pkg/resources/management.cattle.io/v3/globalrole/GlobalRole.md, pkg/resources/management.cattle.io/v3/globalrole/validator.go, pkg/resources/management.cattle.io/v3/globalrole/validator_test.go, pkg/resources/management.cattle.io/v3/globalrolebinding/GlobalRoleBinding.md, pkg/resources/management.cattle.io/v3/projectroletemplatebinding/ProjectRoleTemplateBinding.md
There are open PRs with changes to PRTB, CRTB, Token and other resource validation and mutation. I will update the docs when they are merged.
=> Add docs and tests

pkg/resources/management.cattle.io/v3/clusterroletemplatebinding/validator.go, pkg/resources/management.cattle.io/v3/clusterroletemplatebinding/validator_test.go
The intention was to port any validation logic from Norman to webhook. However upon investigation all the validation already exists in webhook, so I took the opportunity to modify the CRTB to use field errors as mentioned here: https://github.com/rancher/webhook/pull/228#issuecomment-1533735187
| Validation | Status |
|----|------|
| ClusterName is required | existed |
| RoleTemplateName is required | existed |
| RoleTemplate is unlocked | existed |
| Has either a user `userID/userPrincipalID` or group `groupID/groupPrincipalID`| existed |
| Struct Tag Name | Norman Tags |
| ---- | --- |
| UserName | noupdate |
| UserPrincipalName | noupdate |
| GroupName | noupdate |
| GroupPrincipalID | noupdate |
| ClusterName | required, noupdate |
| RoleTemplateName | required, noupdate |
Store: …
=> Convert CRTB validator to use field errors

.github/renovate.json
Change renovate to point to new release branch
=> Update renovate to new release branch

.github/pull_request_template.md
When new people outside of team-1 make Webhook PRs they often do not include unit test or doc updates.
Update the PR template to have the following format so new contributed know what is changes are expected.
No Test or docs are needed for this PR since it is not updating code logic.
=> Update PR template to include repo requirements.

charts/rancher-webhook/Chart.yaml
=> Bump rancher version for 2.8

pkg/generated/controllers/management.cattle.io/factory.go, pkg/generated/controllers/management.cattle.io/interface.go, pkg/generated/controllers/management.cattle.io/v3/cluster.go, pkg/generated/controllers/management.cattle.io/v3/clusterroletemplatebinding.go, pkg/generated/controllers/management.cattle.io/v3/globalrole.go, pkg/generated/controllers/management.cattle.io/v3/globalrolebinding.go, pkg/generated/controllers/management.cattle.io/v3/interface.go, pkg/generated/controllers/management.cattle.io/v3/node.go, pkg/generated/controllers/management.cattle.io/v3/podsecurityadmissionconfigurationtemplate.go, pkg/generated/controllers/management.cattle.io/v3/project.go, pkg/generated/controllers/management.cattle.io/v3/projectroletemplatebinding.go, pkg/generated/controllers/management.cattle.io/v3/roletemplate.go, pkg/generated/controllers/provisioning.cattle.io/factory.go, pkg/generated/controllers/provisioning.cattle.io/interface.go, pkg/generated/controllers/provisioning.cattle.io/v1/cluster.go, pkg/generated/controllers/provisioning.cattle.io/v1/interface.go
Bump copyright year for 0.4 release
=> [v0.4] Bump copyright year

.drone.yml
Update webhook drone to use v2.9 image for integration tests
=> Update to v2.9-head image for integration tests

.github/renovate.json
Update to target the latest release branch and enable the `gomod` manager.
=> [renovate] Update release branch and enabledManagers

README.md, docs.md, go.mod, go.sum, pkg/codegen/main.go, pkg/generated/objects/management.cattle.io/v3/objects.go, pkg/resources/management.cattle.io/v3/setting/Setting.md, pkg/resources/management.cattle.io/v3/setting/validator.go, pkg/resources/management.cattle.io/v3/setting/validator_test.go, pkg/resources/management.cattle.io/v3/userattribute/UserAttribute.md, pkg/resources/management.cattle.io/v3/userattribute/validator.go, pkg/resources/management.cattle.io/v3/userattribute/validator_test.go, pkg/server/handlers.go
=> [v0.3.10] s4: Fixes 227

go.mod, go.sum
=> [v0.4.6] s4: Bump dependencies

README.md, docs.md, go.mod, go.sum, pkg/codegen/main.go, pkg/generated/objects/management.cattle.io/v3/objects.go, pkg/resources/management.cattle.io/v3/setting/Setting.md, pkg/resources/management.cattle.io/v3/setting/validator.go, pkg/resources/management.cattle.io/v3/setting/validator_test.go, pkg/resources/management.cattle.io/v3/userattribute/UserAttribute.md, pkg/resources/management.cattle.io/v3/userattribute/validator.go, pkg/resources/management.cattle.io/v3/userattribute/validator_test.go, pkg/server/handlers.go
Port of #391
* [v0.3.s4] Validate user retention userattribute fields and settings
* [v0.3.s4] Don't allow empty lastLogin user attribute
=> [v0.3] s4: Fixes 227

package/Dockerfile
Bump BCI Micro version to its latest - `15.6`, as `15.5` will be EOL by the end of the year.
=> [v0.5] Bump bci-micro to 15.6

docs.md, pkg/resources/management.cattle.io/v3/setting/Setting.md, pkg/resources/management.cattle.io/v3/setting/validator.go, pkg/resources/management.cattle.io/v3/setting/validator_test.go, pkg/server/handlers.go
https://github.com/rancher/webhook/pull/416 backport for issue https://github.com/rancher/rancher/issues/45589.
https://github.com/rancher/rancher/issues/46057
=> [release/v0.4] Add a check for the agent-tls-mode setting

docs.md, go.mod, pkg/resources/provisioning.cattle.io/v1/cluster/Cluster.md, pkg/resources/provisioning.cattle.io/v1/cluster/mutator.go, pkg/resources/provisioning.cattle.io/v1/cluster/mutator_test.go
Issue: https://github.com/rancher/rancher/issues/45845
Backport of: https://github.com/rancher/webhook/pull/368
=> [v2.8] Add support for allow-dynamic-schema-drop annotation

pkg/resources/management.cattle.io/v3/setting/validator.go, pkg/resources/management.cattle.io/v3/setting/validator_test.go, tests/integration/failPolicy_test.go
=> [v0.4] Set FailurePolicy to Ignore for settings validator

.github/workflows/scripts/integration-test-ci, pkg/server/server.go, pkg/server/server_test.go
=> [main] Use the proper config when fetching mutating webhook configuration

.github/workflows/scripts/integration-test-ci, pkg/server/server.go, pkg/server/server_test.go
=> [v0.4] Use the proper config when fetching mutating webhook configuration

.github/workflows/ci.yaml, .github/workflows/release.yaml
Removing extra spaces, bogus comments, and a duplicate `--set replicas=1`
=> Trivial cleanup changes - no actual effect

package/Dockerfile
Bump BCI Micro version to its latest - `15.6`, as `15.5` will be EOL by the end of the year.
=> [v0.3] Bump bci-micro to 15.6

.github/workflows/ci.yaml
Webhook CI in `main` should test with the CRDs of the `main` branch of rancher/rancher. This is the `:head` rancher/rancher image tag.
=> Update Rancher in CI

charts/rancher-webhook/Chart.yaml
https://github.com/rancher/rancher/issues/44352
Problem in the UI showing an unnecessary warning message
Changed Helm Chart adding a property to avoid that
=> added catalog.cattle.io/managed:true to chart

go.mod, go.sum
=> [v0.3] Bump dependencies

.github/workflows/sync-deps.yaml
=> Fix sync dependency script

.github/workflows/sync-deps.yaml
=> Fix quote for syncing deps workflow

.github/workflows/sync-deps.yaml
We need to use an app token so that the CI of the created PR is triggered.
=> [v0.6] Fix syncing dependencies

.github/workflows/sync-deps.yaml
We need to use an app token so that the CI of the created PR is triggered.
=> [v0.5] Fix syncing dependencies

.github/workflows/sync-deps.yaml
We need to use an app token so that the CI of the created PR is triggered.
=> [v0.4] Fix syncing dependencies

Dockerfile.dapper, go.mod, pkg/codegen/main.go, pkg/resources/common/psa-validation.go, pkg/resources/management.cattle.io/v3/feature/validator.go
=> [release/v0.5] Upgrade go version to 1.23

Dockerfile.dapper, go.mod, pkg/codegen/main.go, pkg/resources/common/psa-validation.go, pkg/resources/management.cattle.io/v3/feature/validator.go
=> [main] Upgrade go version to 1.23

.github/renovate.json, README.md, VERSION.md
=> Add versioning information and update renovate

pkg/resources/core/v1/namespace/projectannotations.go, pkg/resources/core/v1/namespace/projectannotations_test.go, pkg/resources/core/v1/namespace/validator.go, pkg/resources/core/v1/namespace/validator_test.go, pkg/resources/management.cattle.io/v3/cluster/validator.go, pkg/resources/management.cattle.io/v3/cluster/validator_test.go, pkg/resources/provisioning.cattle.io/v1/cluster/validator.go
=> Revert "[release/v0.6] Prevent deletion of `local` cluster (#551)"

pkg/resources/core/v1/namespace/projectannotations.go, pkg/resources/core/v1/namespace/projectannotations_test.go, pkg/resources/core/v1/namespace/validator.go, pkg/resources/core/v1/namespace/validator_test.go, pkg/resources/management.cattle.io/v3/cluster/validator.go, pkg/resources/management.cattle.io/v3/cluster/validator_test.go, pkg/resources/provisioning.cattle.io/v1/cluster/validator.go
=> Revert "[release/v0.5] Prevent deletion of `local` cluster (#551)"

pkg/resources/core/v1/namespace/projectannotations.go, pkg/resources/core/v1/namespace/projectannotations_test.go, pkg/resources/core/v1/namespace/validator.go, pkg/resources/core/v1/namespace/validator_test.go, pkg/resources/management.cattle.io/v3/cluster/validator.go, pkg/resources/management.cattle.io/v3/cluster/validator_test.go, pkg/resources/provisioning.cattle.io/v1/cluster/validator.go
This reverts commit b786408cca6645fd54435239717332f0e79c9915.
=> Revert "Prevent deletion of `local` cluster (#551)"

go.mod, go.sum
https://github.com/rancher/rancher/issues/46908
=> [release/v0.6] Change lasso with tagged release

go.mod, go.sum
https://github.com/rancher/rancher/issues/46908
=> [release/v0.5] Change lasso with tagged release

.github/workflows/scripts/start-rancher.sh
Fixes:  https://github.com/rancher/rancher/issues/49291
=> Disable Imperative API for webhook integration tests

pkg/resources/auditlog.cattle.io/v1/auditpolicy/validator.go, pkg/resources/auditlog.cattle.io/v1/auditpolicy/validator_test.go, pkg/server/handlers.go
Original PR missed commit to actually register the handler.
Register the validation handler.
=> [main] register AuditPolicy webhook validation handler

docs.md, pkg/resources/provisioning.cattle.io/v1/cluster/Cluster.md, pkg/resources/provisioning.cattle.io/v1/cluster/validator.go, pkg/resources/provisioning.cattle.io/v1/cluster/validator_test.go
https://github.com/rancher/rancher/issues/51041
backport of https://github.com/rancher/webhook/pull/985
=> [backport] [2.11] add validation for etcd s3 cloud credential

docs.md, pkg/resources/provisioning.cattle.io/v1/cluster/Cluster.md, pkg/resources/provisioning.cattle.io/v1/cluster/validator.go, pkg/resources/provisioning.cattle.io/v1/cluster/validator_test.go
https://github.com/rancher/rancher/issues/51040 
backport of https://github.com/rancher/webhook/pull/985
=> [backport] [2.12] add validation for etcd s3 cloud credential

docs.md, pkg/resources/management.cattle.io/v3/users/User.md, pkg/resources/management.cattle.io/v3/users/validator.go, pkg/resources/management.cattle.io/v3/users/validator_test.go
Backport of https://github.com/rancher/webhook/pull/1016 and https://github.com/rancher/webhook/pull/943
=> [v0.8] Introduce username validation

docs.md, pkg/resources/management.cattle.io/v3/users/User.md, pkg/resources/management.cattle.io/v3/users/validator.go, pkg/resources/management.cattle.io/v3/users/validator_test.go
Backport of https://github.com/rancher/webhook/pull/1023
=> [v0.5] Introduce username validation
