go.mod, go.sum, main.go, pkg/generated/controllers/management.cattle.io/factory.go, pkg/generated/controllers/management.cattle.io/v3/cluster.go, pkg/resources/globalrolebinding/globarolebinding.go
Issue:
- https://github.com/rancher/rancher/issues/33429
These changes pull in a new wrangler version which has a fix for a panic in the webhook handler logic. Also included is allowance for update & delete of GRBs if the corresponding GR isn't found, i.e. it was deleted. Updates to GRBs are only allowed if the DeletionTimestamp != nil, this only allows updates to finalizers when there is no associated GR
=> [release/v0.1] Fix for panic and to allow GRB deletion

pkg/server/server.go
The validationPath was accidentally used for the mutation service
config. This change alters this to use the mutationPath.
=> Use mutationPath for mutation service config

.gitignore, .golangci.json, go.mod, main.go, pkg/codegen/main.go, pkg/codegen/template.go, pkg/generated/objects/management.cattle.io/v3/objects.go, pkg/generated/objects/provisioning.cattle.io/v1/objects.go, pkg/resources/mutation/cluster/provisioningcluster.go, pkg/resources/mutation/fleetworkspace/fleetworkspace.go, pkg/resources/validation/clusterroletemplatebinding/clusterrtb.go, pkg/resources/validation/globalrole/globalrole.go, pkg/resources/validation/globalrolebinding/globarolebinding.go, pkg/resources/validation/projectroletemplatebinding/projectrtb.go, pkg/resources/validation/roletemplate/roletemplate.go
In order to validate objects, the new and old objects, if they exist,
should be pull from the webhook request. This process is identical for
all objects except that the return types would be different. This is a
candidate for code generation, and this generation is added.
=> Add generation for getting objects from requests

pkg/resources/validation/cluster/cluster.go, pkg/resources/validation/cluster/provisioningcluster.go
When a v1.Cluster is created/updated, the ACE configuration should be
validated. The webhook will respond with an error if a cert is provided
without a FQDN.
Issue:
https://github.com/rancher/rancher/issues/32388
=> Add ACE validation for v1.Clusters

pkg/resources/validation/cluster/provisioningcluster.go
The validation of ACE config is dependent on the fact that the RKEConfig
is not nil. Checking for non-nil RKEConfig is added.
=> Check for RKEConfig for ACE validation

pkg/resources/validation/cluster/provisioningcluster.go, pkg/server/validation.go
Problem:
Any cloud cred can be used without permissions to view that secret
Solution:
Validate user creating or modifying the provisioning cluster has get
access to the referenced cloudCredential. When modifying the cluster,
permission is only checked if the cloudCred changes from existing. The
users permissions on the cluster say if they can use the existing
cloudCred.
This supports both old and new style cloudCred naming and namespace
=> Check provisioning cluster for cloudCred access

charts/rancher-webhook/templates/_helpers.tpl, charts/rancher-webhook/templates/pre-delete-hook-cluster-role-binding.yaml, charts/rancher-webhook/templates/pre-delete-hook-cluster-role.yaml, charts/rancher-webhook/templates/pre-delete-hook-job.yaml, charts/rancher-webhook/templates/pre-delete-hook-service-account.yaml, charts/rancher-webhook/values.yaml
Issue https://github.com/rancher/rancher/issues/33988
Cause:
When rancher-webhook is uninstalled, it will leave the resource `MutatingWebhookConfiguration` named `rancher.cattle.io`, which prevents us from re-installing Rancher into the cluster. 
Fixes:
We need to fix the rancher-webhook chart such that it will delete the MutatingWebhookConfiguration when the app is uninstalled. 
`Pre-delete-hook` is used here because 
- we can run a `Job` successfully only when either both the `MutatingWebhookConfiguration`  and `Validatingwebhookconfigurations` exist or not
- and because the `MutatingWebhookConfiguration` is not part of the helm chart, so Helm cleans only the 
`Validatingwebhookconfigurations` by itself
- therefore, we have to use the pre-delete-hook to remove both of them before Helm …
=> add a pre-delete-hook to clean up mutatingwebhookconfigurations

charts/rancher-webhook/templates/pre-delete-hook-psp.yaml
Issue https://github.com/rancher/rancher/issues/34508
add the missing check in one of the templates to match the behavior of other templates for pre-delete-hook
The fix should not affect any functionality of the chart. 
The chart is not used by users directly, and the default setting is to `preDelete.enabled: true`, So no behavior will be changed. 
Update: this fix will be merged for rancher 2.6.1 
TODO:
=> add the missing check in  one of the template

go.mod, go.sum, pkg/server/rules.go, pkg/server/server.go, pkg/server/validation.go
Issue: 
- https://github.com/rancher/rancher/issues/34691
When MCM is disabled we are not mounting RBAC resource validation routes in the webhook. This needs to also be reflected in the webhook configurations. As part of this I moved the rules out of the server.go file
=> Omit rules from webhook configs if mcm is disabled

pkg/server/rules.go, pkg/server/server.go
A previous change mistakenly added a mutation webhook configuration for
global role bindings. This change removes this configuration because
there are no such webhooks.
=> Remove mutation webhook config for global role bindings

pkg/resources/validation/cluster/provisioningcluster.go, pkg/resources/validation/cluster/provisioningcluster_test.go, pkg/server/validation.go
Users should not be able to create a cluster with name 'local' or of the
form 'c-xxxxx' because this conflicts with logic related to v3.Clusters.
The webhook now checks for such names and denies creates.
Issue:
https://github.com/rancher/rancher/issues/33694
=> Validate provisioning cluster names on create

go.mod, go.sum, pkg/server/server.go
Tested using a modified version of `./scripts/build` and `k3d`:
```bash
#!/bin/bash
set -e
if kubectl get ns cattle-system; then
kubectl delete ns cattle-system
fi
source $(dirname $0)/version
cd $(dirname $0)/..
mkdir -p bin
LINKFLAGS="-X github.com/rancher/webhook.Version=$VERSION"
LINKFLAGS="-X github.com/rancher/webhook.GitCommit=$COMMIT $LINKFLAGS"
GOOS=darwin go build -ldflags "$LINKFLAGS" -o bin/webhook
kubectl create ns cattle-system
./bin/webhook
```
End date is expected value:
```bash
% k get secrets -n cattle-system cattle-webhook-tls -o json | jq -r ".data.\"tls.crt\"" | base64 -d | openssl x509 -enddate
notAfter=Nov 17 19:20:28 2031 GMT
```
Relevant issue: https://github.com/rancher/rancher/issues/35366
=> Set certificate expiration to 10 years by default

go.mod, go.sum, main.go
Related to https://github.com/rancher/rancher/issues/36079.
We should make a new tag for webhook - v0.2.4-rc3. This updates the latest webhook with the latest changes of dynamiclistener. Rancher v2.6.3's webhook is not using the latest dynamiclistener, it misses a commit that fixed the behavior of automatic cert update when a cert is close to expiration (https://github.com/rancher/dynamiclistener/commit/284cc004e84101e4a5b9fa50c00e101095db83f6).
Let's update the dynamiclistener for the newest webhook to be used in Rancher 2.6.4.
Wrangler is updated in the dynamiclistener, and so webhook must update it too. That's why there is a change in `main.go` to accommodate for the slight top-level Wrangler API change.
=> Update the versions of dynamiclistener and wrangler (by extension)

pkg/codegen/main.go, pkg/generated/objects/core/unstructured/objects.go, pkg/patch/patch.go, pkg/resources/mutation/machineconfigs/machineconfigs.go, pkg/resources/mutation/mutation.go, pkg/resources/mutation/secret/secret.go, pkg/resources/validation/cluster/provisioningcluster.go, pkg/resources/validation/machineconfig/machineconfig.go, pkg/resources/validation/validation.go, pkg/server/mutation.go, pkg/server/rules.go, pkg/server/validation.go
In order to provide RBAC access to rke-machine-configs created by a user, a
creatorID annotation is added as a mutation webhook on create. In addition, a
validation webhook is added, similar to the provisioning cluster objects, so
that the creatorID annotation can only be updated in certain situations.
Issue:
https://github.com/rancher/rancher/issues/35868
=> Add mutation/validation webhooks for rke-machine-configs

charts/rancher-webhook/templates/pre-delete-hook-job.yaml
No default securityContext is defined for the pre-delete job, so we end up getting an error like:
```
container has runAsNonRoot and image will run as root (pod: "rancher-webhook-pre-delete-v6bqp_cattle-system(a90e6d04-3086-41ff-876a-52401bd25d56)
```
To fix, I've added a securityContext to the pod that marks it as running as user 0 (aka root).
Related Issue: https://github.com/rancher/rancher/issues/33724
=> Run pre-delete-hook-job as root

go.mod, go.sum, main.go, pkg/generated/controllers/management.cattle.io/factory.go, pkg/generated/controllers/management.cattle.io/interface.go, pkg/generated/controllers/management.cattle.io/v3/cluster.go, pkg/generated/controllers/management.cattle.io/v3/globalrole.go, pkg/generated/controllers/management.cattle.io/v3/interface.go, pkg/generated/controllers/management.cattle.io/v3/roletemplate.go
Related to https://github.com/rancher/rancher/issues/36177.
Cherry-pick commits from tag `v0.2.3` until and including the dynamic listener update commit – to enable automatic cert renewal.
Once this PR is merged, I will tag the resulting latest commit as `v0.2.4` (to be used only in the `v2.6.3-patch1` release).
=> [v2.6.3 patch1] Include changes of webhook certificate auto-renewal

pkg/resources/validation/clusterroletemplatebinding/clusterrtb.go, pkg/resources/validation/projectroletemplatebinding/projectrtb.go
These changes bring the CRTB and PRTB CRs more in line with the underlying k8s RBAC types, which disallow updates to RoleRef. This also addresses a bug with Apply in Rancher, where a CRTB can't be synced because a RoleBinding is applied with a different RoleRef after the CRTB had it's RoleTemplateName updated
=> Update CRTB/PRTB validation handlers to disallow RoleTemplateName updates

charts/rancher-webhook/Chart.yaml, charts/rancher-webhook/templates/_helpers.tpl, charts/rancher-webhook/templates/deployment.yaml, charts/rancher-webhook/templates/pre-delete-hook-job.yaml, charts/rancher-webhook/values.yaml
Adding default toleration/node selector to ensure webhook pods
are scheduled on linux nodes. Related to rancher/rancher#36401
=> Adding default linux tolerations and node selectors

pkg/resources/validation/cluster/provisioningcluster.go, pkg/resources/validation/cluster/provisioningcluster_test.go
Issues:
https://github.com/rancher/rancher/issues/37535
https://github.com/rancher/rancher/issues/37544
Although the cluster name can be 253 characters, the cluster name is put in
several labels by both Rancher and CAPI controllers. Therefore, the name should
really be limited to 63 characters.
This change includes this validation in the name validation webhook for the
provisioning cluster objects.
=> Limit provisioning cluster name to 63 characters

scripts/package-helm
Package script didn't anchor the version regex causing the
kube-version/rancher-version to be errantly overwritten
=> Fixing package script bug

go.mod, pkg/mocks/RoleTemplateCache.go, pkg/resources/validation/roletemplate/roletemplate.go, pkg/resources/validation/roletemplate/roletemplate_test.go, pkg/server/validation.go
When 2 role templates inherit from each other, this can cause
performance issues or an outright crash. This change aims to
ensure that role templates can't form circular references like
this in the future.
=> Adds check for circular references to RoleTemplates

charts/rancher-webhook/Chart.yaml
updates rancher version in charts.
=> Prepare rancher-webhook charts for rancher 2.7.

.drone.yml
Drone CI is currently broken on the github release phase. It looks like the github release plugin removed support for arm v32 (see https://github.com/drone-plugins/drone-github-release/pull/143), so we are pinning to a version which recently worked, for this phase.
=> Fix for 2.5 pipeline on github release phase

charts/rancher-webhook/templates/pre-delete-hook-cluster-role.yaml, charts/rancher-webhook/templates/pre-delete-hook-psp.yaml
Don't deploy the PSP or include the psp rule in the cluster role if PSPs aren't supported.
https://github.com/rancher/rancher/issues/39854
=> Check for PSP compatibility

charts/rancher-webhook/charts/capi/templates/service.yaml, charts/rancher-webhook/templates/service.yaml
This will require a new PR to allow the webhook to run properly in the downstream
=> Revert charts changes

charts/rancher-webhook/templates/deployment.yaml
Since rancher-webhook will take care of its own cert generation, we only need to include the secret/volume for use by capi when capi is enabled.
=> Update webhook deployment to require rancher-webhook-tls only when capi is enabled

pkg/generated/controllers/management.cattle.io/factory.go, pkg/generated/controllers/management.cattle.io/interface.go, pkg/generated/controllers/management.cattle.io/v3/cluster.go, pkg/generated/controllers/management.cattle.io/v3/clusterroletemplatebinding.go, pkg/generated/controllers/management.cattle.io/v3/globalrole.go, pkg/generated/controllers/management.cattle.io/v3/interface.go, pkg/generated/controllers/management.cattle.io/v3/projectroletemplatebinding.go, pkg/generated/controllers/management.cattle.io/v3/roletemplate.go, pkg/generated/controllers/provisioning.cattle.io/factory.go, pkg/generated/controllers/provisioning.cattle.io/interface.go, pkg/generated/controllers/provisioning.cattle.io/v1/cluster.go, pkg/generated/controllers/provisioning.cattle.io/v1/interface.go
Updates the Copywrite header in our generated files to 2023.
=> Go generate.

scripts/integration-test, scripts/test
The integration test binary was being uploaded into the release assets because of the code section [here](https://github.com/rancher/webhook/blob/716525619509df709ec3e1ddcb5304f2f3a9e736/scripts/package#L28-#L36) 
I updated the name of the integration test binary so that it no longer matches the expression.
=> Rename integration test

pkg/podsecurityadmission/podsecurityadmission.go, pkg/podsecurityadmission/podsecurityadmission_test.go, pkg/resources/mutation/cluster/cluster.go, pkg/resources/validation/cluster/cluster.go
Issue https://github.com/rancher/rancher/issues/39992
Problem:
Different API versions for `PodSecurityConfiguration` is used in different k8s versions: the API version `v1beta1` is used in k8s 1.23 and 1.24;  `v1` is used in k8s 1.25 and above. 
Previously, the mutator used version `v1` when mutating  RKE1  1.23 and 1.24 clusters, which failed to provision clusters due to the error of `API version is unknown`.
Fix:
This PR allows the mutator to auto-adjust the API version of the PodSecurityConfiguration resource based on the cluster k8s version. 
Tests:
The test is done by running the webhook locally and pointing it to a Rancher setup.  The provision of the RKE1 cluster with k8s version 1.23, 1,24, and 1,25 all succeed.
=> Auto-adjust the API version of the PodSecurityConfiguration resource based on the cluster k8s version

scripts/build
Variables are correctly substituted at build time with this change.
Current:
```
INFO[0000] Rancher-webhook version dev (HEAD) is starting 
```
This change:
```
INFO[0000] Rancher-webhook version 0.0.0-6187da1 (6187da1) is starting
```
=> [release/v0.3] Print correct version on startup

pkg/server/handlers.go
Issue: https://github.com/rancher/rancher/issues/39365
Problem:
The handler for PSACT(PodSecurityAdmissionConfiguraTiontemplate) runs when the rancher-webhook app is installed in a downstream cluster, which causes the degradation of RBAC-related validation.  
By design, The handler for PSACT(PodSecurityAdmissionConfiguraTiontemplate) should run only in the local cluster, and it needs to get the v1 provisioning Cluster objects to perform its validations.  
Fix:
Move the handler to the correct section, so it runs only when MultiClusterManagement is enabled which is in the local cluster. 
Tests:
1. The fix is tested by running the webhook locally but pointing it to a downstream RKE2 cluster in Rancher. 
When I am trying to create a namespace and set PSA labels  as the project member, I see …
=> Run the handler for PSACT only when MCM is enabled

pkg/resources/validation/podsecurityadmissionconfigurationtemplate/podsecurityact.go, pkg/resources/validation/podsecurityadmissionconfigurationtemplate/podsecurityact_test.go
When creating `PodSecurityAdmissionConfiguration` objects in Kubernetes you are able to omit fields within the `defaults` section without issue. Prior implementation of the validation for Rancher's specific `PodSecurityAdmissionConfigurationTemplates` required users to provide a valid value for the level and version attributes of each `defaults` element. 
This PR modifies the validating web-hook for the `PodSecurityAdmissionConfigurationTemplate` CRD so that the behavior seen in Rancher matches the behavior seen in Kubernetes. Now, users can omit a level, version, or both when defining the `defaults` of a `PodSecurityAdmissionConfigurationTemplate`. If you do provide a value, it must be either `restricted`, `privileged`, or `baseline`
+ build a local image of the modified webhook
+ modify …
=> [2.7] Update PSACT validation rules

pkg/resources/validation/podsecurityadmissionconfigurationtemplate/podsecurityact.go, pkg/resources/validation/podsecurityadmissionconfigurationtemplate/podsecurityact_test.go
Issue: https://github.com/rancher/rancher/issues/40478
Because we decided to rename the two built-in PSACTs to have a prefix of `rancher-`, we need to update the checks for names here. 
Once this PR is merged and a new tag is cut,  [This PR in rancher/rancher](https://github.com/rancher/rancher/pull/40479) will be updated to include both the name changing and chart version bumping.
=> update the names of Rancher builtin PSACTs

pkg/resolvers/aggregateResolver_test.go, pkg/resolvers/crtbResolver.go, pkg/resolvers/crtbResolver_test.go, pkg/resolvers/prtbResolver.go, pkg/resolvers/prtbResolver_test.go, pkg/resolvers/resolvers.go, pkg/resolvers/resolvers_test.go, pkg/resources/validation/clusterroletemplatebinding/clusterrtb.go, pkg/resources/validation/clusterroletemplatebinding/clusterrtb_test.go, pkg/resources/validation/projectroletemplatebinding/projectrtb.go, pkg/resources/validation/projectroletemplatebinding/projectrtb_test.go, pkg/server/handlers.go
Forward Port: https://github.com/rancher/webhook/pull/195
This commit updates the CRTB and PRTB ruleResolvers to use CRTBs and PRTBs with matching groups as well as matching usernames. This commit also updates the caches used by the resolvers to have a new indexer that index on a composite key of the binding subject and the clusterName or ProjectName of the binding.
=> Adds group checking to ruleResolvers.

Dockerfile.dapper
- Updates to latest
- Puts `HELM_VERSION` in environment variable so it can be automatically updated, see https://github.com/rancher/renovate-config/blob/main/default.json#L27
=> Helm version in env var to automatically update

.drone.yml, charts/rancher-webhook/templates/deployment.yaml, scripts/integration-test, scripts/version
Issue: https://github.com/rancher/rancher/issues/40824
Added the startup probe to the rancher-webhook chart so that the Webhook does not appear to be ready before it has updated the validating webhook configuration.
The startup probe checks every 5 seconds for 10 minutes before declaring that the webhook failed to start.
These values seemed reasonable to me but are up for discussion. `5s periodSeconds * 120 failureThreshold`
In the second commit, I updated the integration test to install the newly packaged charts created in CI to provide us with a larger test coverage. I also added a command that will start tailing the rancher logs if Rancher-Webhook fails to deploy after 5 minutes.
=> Add Startup probe to charts.

pkg/server/handlers.go
rancher/rancher#41613
The secrets mutator, which has the default failPolicy of `fail` was running in downstream clusters. This was creating edge cases where internal k8s operations on downstream clusters (outlined in the above cases) would fail.
The secrets mutator will only run in the local cluster, which is the only cluster where it is required.
Ran basic test case - mutator was registered in local but not in remote. The logs were also clear of errors.
=> Adjusting secrets mutator to only run in local

Dockerfile.dapper, charts/rancher-webhook/charts/capi/templates/service.yaml, charts/rancher-webhook/templates/deployment.yaml, charts/rancher-webhook/templates/service.yaml, charts/rancher-webhook/tests/README.md, charts/rancher-webhook/tests/capi-service_test.yaml, charts/rancher-webhook/tests/deployment_test.yaml, charts/rancher-webhook/tests/service_test.yaml, charts/rancher-webhook/values.yaml, dev-scripts/helm-unittest.sh, pkg/capi/capi.go, pkg/server/server.go, scripts/ci, scripts/integration-test, scripts/package-helm, scripts/test-helm, scripts/validate-ci, tests/integration/port_test.go
First Commit: 
Adds the ability to customize the ports used by the webhook via helm values. 
Integration tests were updated to stop the running Rancher instance from downgrading the webhook during the tests.
To fix this, the test run rancher for the initial webhook installation. Then Rancher is stopped, and K3s is manually started.
=> Adds the ability to set custom ports for Webhook.

pkg/resources/management.cattle.io/v3/projectroletemplatebinding/validator.go, pkg/resources/management.cattle.io/v3/projectroletemplatebinding/validator_test.go, tests/integration/projectRoleTemplateBinding_test.go
Remaining validation logic from Norman needs to be ported over to the Webhook.
1. Validators
exists = Role template must exist.
exists = Role template must be unlocked.
**new  = Role template must belong to its appropriate context (project).**
exists = Either user/userPrincipal OR group/groupPrincipal must exist.
2. Struct tags
UserName           norman:"noupdate,type=reference[user]"
UserPrincipalName  norman:"noupdate,type=reference[principal]"
GroupName          norman:"noupdate,type=reference[group]"
GroupPrincipalName norman:"noupdate,type=reference[principal]"
ProjectName        norman:"required,noupdate,type=reference[project]"
RoleTemplateName   norman:"required,noupdate,type=reference[roleTemplate]"
**new =   ServiceAccount     norman:"nocreate,noupdate"** - will only implement …
=> Port remaining PRTB validation rules from Norman

docs.md, pkg/codegen/main.go, pkg/generated/objects/management.cattle.io/v3/objects.go, pkg/resources/management.cattle.io/v3/project/Project.md, pkg/resources/management.cattle.io/v3/project/mutator.go, pkg/resources/management.cattle.io/v3/project/mutator_test.go, pkg/resources/management.cattle.io/v3/project/quota_validate.go, pkg/resources/management.cattle.io/v3/project/validator.go, pkg/resources/management.cattle.io/v3/project/validator_test.go, pkg/server/handlers.go, tests/integration/project_test.go
New validations:
- prohibit deleting the system project
- check that quota fields are consistent with one another and sufficient
for existing quota usage
New mutations:
- adds creator-role-bindings annotation
Refactor code that was largely copied from the norman store in Rancher:
- rename variables and functions for clarity
- break up functions into logical units
- rename imports according to standard conventions and for clarity
- remove the ephemeral updates to the used quota object,
quotav1.LessThanOrEqual already does not compare resources that aren't
present in both objects[1]
- remove project mutex. Only one goroutine (the webhook) should be
accessing the project and its namespaces. Callers (rancher/rancher)
should implement their own lock before counting namespaces.
[1] …
=> Add validation and mutation for Projects

README.md, charts/rancher-webhook/templates/deployment.yaml, charts/rancher-webhook/templates/secret.yaml, charts/rancher-webhook/tests/deployment_test.yaml, charts/rancher-webhook/values.yaml, main.go, pkg/server/server.go
Add the ability to authenticate incoming requests, verifying that all requests originate from the Kubernetes API server and no where else.
Authenticating the API server requires manual steps to configure both the API server and the webhook. Follow the Kubernetes webhook documentation[1] to create an admission configuration and kubeconfig for the API server, and update the kube-apiserver flags to use them. Only cert-based authentication is supported, basic auth and token authentication will not be recognized. Then, set auth.clientCA in the webhook chart's values.yaml to the base64-encoded CA for the certs, and set auth.allowedCNs to the CN for the client cert the apiserver will present.
[1] https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#authenticat …
=> Add cert-based API server authentication

pkg/resources/management.cattle.io/v3/projectroletemplatebinding/validator.go, pkg/resources/management.cattle.io/v3/projectroletemplatebinding/validator_test.go
The webhook rejects a request that updates any PRTB that already has ServiceAccount field **set**.
Instead, it should reject attempts to **change** it. Adjust the logic accordingly.
=> [0.3] Disallow changes to ServiceAccount field on PRTB update rather than its presence

pkg/resources/management.cattle.io/v3/projectroletemplatebinding/validator.go, pkg/resources/management.cattle.io/v3/projectroletemplatebinding/validator_test.go
The webhook rejects a request that updates any PRTB that already has ServiceAccount field **set**.
Instead, it should reject attempts to **change** it. Adjust the logic accordingly.
=> Disallow changes to ServiceAccount field on PRTB update rather than its presence

go.mod, go.sum, scripts/integration-test
CI in rancher which uses the new webhook is currently failing. This updates the Rancher/pkg/apis import to use new types to resolve the CI failures, and adds a temporary ci change to allow CI in the webhook to pass.
=> Api version bump

pkg/resources/management.cattle.io/v3/nodedriver/validator.go, pkg/resources/management.cattle.io/v3/nodedriver/validator_test.go, pkg/server/handlers.go
When two Node Drivers share the same name deleting/disabling them goes through the rancher-webhook, which will admit the request if no nodes are using them and subsequently delete the CRDs associated with one or the other, which may end up removing the wrong CRDs and put the cluster in a weird state. The only way to fix this would be to wait for the reconciler to run again and recreate them.
Another side effect here is that if the CRDs are not present (like it takes a bit for the items to download) the request is not admitted which is a race condition.
The first part will be switching the check to go off of the `.spec.DisplayName` instead to `.objectMeta.Name`, that way the check will be globally unique.
The second part will just be fixiable by adding a check to see if the CRD exists …
=> Fix NodeDriver validation to ensure uniqueness + prevent race condition of CRD creation

pkg/resources/management.cattle.io/v3/globalrole/validator.go, pkg/resources/management.cattle.io/v3/globalrole/validator_test.go
Users could update a globalRole that was not a builtIn to be a builtin role.
When a previously non-builtIn role is updated we check if it is being changed to a builtIn role.
=> Disallows the updating GlobalRoles to be builtin.

docs.md, pkg/resources/management.cattle.io/v3/projectroletemplatebinding/ProjectRoleTemplateBinding.md, pkg/resources/management.cattle.io/v3/projectroletemplatebinding/validator.go, pkg/resources/management.cattle.io/v3/projectroletemplatebinding/validator_test.go, tests/integration/projectRoleTemplateBinding_test.go
Users aren't forbidden to create a badly configured PRTB where the namespace and the project ID part of `projectName` don't match.
For example:
```yaml
apiVersion: management.cattle.io/v3
kind: ProjectRoleTemplateBinding
metadata:
name: test
namespace: p-cgtq4
projectName: c-some-cluster:foobar
roleTemplateName: configmaps-manage
userName: u-tgws8
```
A valid PRTB example would have a namespace `p-cgtq4` and projectName `c-some-cluster:p-cgtq4`.
If users are allowed to specify the project ID and namespace different, there are two problems:
1. A Rancher controller will continuously fail to sync the RBAC objects to the cluster
2. If a namespace exists but doesn't equal the project ID, then the PRTB will never be cleaned up when the actual project (for which the binding was intended) gets …
=> Don't allow PRTB namespace and the project ID of projectName to differ

docs.md, pkg/resources/management.cattle.io/v3/clusterroletemplatebinding/ClusterRoleTemplateBinding.md, pkg/resources/management.cattle.io/v3/clusterroletemplatebinding/validator.go, pkg/resources/management.cattle.io/v3/clusterroletemplatebinding/validator_test.go, tests/integration/clusterRoleTemplateBinding_test.go
Users can create CRTBs that have different namespaces and ClusterNames. That causes their deletion to fail when the cluster is deleted. It also doesn't appear in the UI as intended.
- Added a check on CREATE to ensure that the namespace and custerName are the same. Deny the request if they are mismatched
- Added the same check on UPDATE, but just provide a warning to the user and allow it.
I also fixed the wording of one of the error messages to be more clear.
=> Prevent CRTBs from being created with mismatching Namespace and ClusterName

docs.md, pkg/resources/management.cattle.io/v3/fleetworkspace/FleetWorkspace.md, pkg/resources/management.cattle.io/v3/fleetworkspace/mutator.go, pkg/resources/management.cattle.io/v3/fleetworkspace/mutator_test.go
https://github.com/rancher/fleet/issues/1519
Rancher allows the creation of fleet workspaces even though the namespace already exists. Deleting that workspace causes the deletion of namespace along with its contents. Deleting unwanted fleet workspace results in data loss.
Reject the workspace creation if namespace already exists
=> Reject workspace creation if namespace already exists

charts/rancher-webhook/Chart.yaml
https://github.com/rancher/rancher/issues/42949 needed to complete https://github.com/rancher/rancher/issues/41789
The minimum kube-version is not set to `1.23.0-0`.
Increase the minimum kube-version to `1.23.0-0`
=> Update minimum kube version to 1.23

docs.md, pkg/resolvers/grbClusterResolver.go, pkg/resolvers/grbClusterResolver_test.go, pkg/resolvers/resolvers_test.go, pkg/resources/management.cattle.io/v3/globalrole/GlobalRole.md, pkg/resources/management.cattle.io/v3/globalrole/setup_test.go, pkg/resources/management.cattle.io/v3/globalrolebinding/GlobalRoleBinding.md, pkg/resources/management.cattle.io/v3/globalrolebinding/validator_test.go, pkg/server/handlers.go
Adds an exception for the fleet/backup-restore service accounts for the `inheritedClusterRoles` escalation check
The escalation check for the `inheritedClusterRoles` field currently only allows users to grant permissions through this field (either by modifying the globalRole or any associated binding) if one of two items is true:
- The user possess rules that they are trying to give, specifically through the `inheritedClusterRoles` field. 
- This means that a user can only give out (for example) `clusterOwner` if they have been assigned `clusterOwner` in the `inheritedClusterRoles` field of a globalRole.
- The user is an admin/restricted admin
- The code treats the global roles (with these names) as having `clusterOwner` in the `inheritedClusterRoles` field.
This behavior caused issues …
=> Adding SA exceptions to gr escalation

docs.md, pkg/resources/management.cattle.io/v3/project/Project.md, pkg/resources/management.cattle.io/v3/project/validator.go, pkg/resources/management.cattle.io/v3/project/validator_test.go
The clusterName field of projects was already immutable in effect since it needed to match the namespace, which is immutable. This makes it explcitly immutable, and changes the check for cluster existence to only occur on create requests
rancher/rancher#42999
On both create and update, the webhook validates that the ClusterName field refers to a valid cluster. This causes issues when a cluster is deleted - a controller then needs to remove a finalizer added to a project to allow the project to be deleted. Since the cluster no longer exists, the finalizer can't be removed, and the project is indefinitely locked in a deleting state.
Now, the clusterName integrity check (validating that the `management.cattle.io/Cluster` object specified by `ClusterName` exists) only runs on create. …
=> Make project.spec.ClusterName immutable

docs.md, pkg/auth/escalation.go, pkg/auth/escalation_test.go, pkg/auth/globalrole.go, pkg/auth/globalrole_test.go, pkg/resolvers/grbClusterResolver.go, pkg/resolvers/grbClusterResolver_test.go, pkg/resolvers/resolvers_test.go, pkg/resources/management.cattle.io/v3/globalrole/GlobalRole.md, pkg/resources/management.cattle.io/v3/globalrole/setup_test.go, pkg/resources/management.cattle.io/v3/globalrole/validator.go, pkg/resources/management.cattle.io/v3/globalrole/validator_test.go, pkg/resources/management.cattle.io/v3/globalrolebinding/GlobalRoleBinding.md, pkg/resources/management.cattle.io/v3/globalrolebinding/setup_test.go, pkg/resources/management.cattle.io/v3/globalrolebinding/validator.go, pkg/resources/management.cattle.io/v3/globalrolebinding/validator_test.go, pkg/resources/management.cattle.io/v3/roletemplate/validator.go, pkg/server/handlers.go
Aims to resolve several issues with creating/updating GRs/GRBs
GlobalRoles and GlobalRoleBindings can only be created/updated by users with equivalent permissions. This created issues for things like service accounts, which were unable to gain permissions in specific fields (such as inherited cluster roles).
This PR adds support for two new verbs (both on GlobalRoles):
- escalate
- Users with this verb can create GlobalRoles that have permissions higher than the permissions they possess
- bind
- Users with this verb can create GlobalRoleBindings to GlobalRoles that have permissions higher than the permissions that they possess
- Note that the permissions here must be on the GlobalRole that the binding is made to, not the binding crd
Upstream docs on this field can be found here: …
=> Adds Support for Escalate and Bind verb to GRs/GRBs

pkg/resources/management.cattle.io/v3/nodedriver/validator.go, pkg/resources/management.cattle.io/v3/nodedriver/validator_test.go, pkg/server/handlers.go
This reverts commit 3ed3c681186d02d5d414869126ad6a9fdd38698f, reversing changes made to ddb05820d48f7fcc0774e7d2fbfad54d66af7232 as part of https://github.com/rancher/rancher/issues/42378.
Custom out-of-tree (not builtin) node drivers are still using the `nd-xxxxx` autogenerated name for creation.
Revert #277
=> Revert "Merge pull request #277"

pkg/generated/controllers/management.cattle.io/factory.go, pkg/generated/controllers/management.cattle.io/interface.go, pkg/generated/controllers/management.cattle.io/v3/cluster.go, pkg/generated/controllers/management.cattle.io/v3/clusterroletemplatebinding.go, pkg/generated/controllers/management.cattle.io/v3/globalrole.go, pkg/generated/controllers/management.cattle.io/v3/globalrolebinding.go, pkg/generated/controllers/management.cattle.io/v3/interface.go, pkg/generated/controllers/management.cattle.io/v3/node.go, pkg/generated/controllers/management.cattle.io/v3/podsecurityadmissionconfigurationtemplate.go, pkg/generated/controllers/management.cattle.io/v3/project.go, pkg/generated/controllers/management.cattle.io/v3/projectroletemplatebinding.go, pkg/generated/controllers/management.cattle.io/v3/roletemplate.go, pkg/generated/controllers/provisioning.cattle.io/factory.go, pkg/generated/controllers/provisioning.cattle.io/interface.go, pkg/generated/controllers/provisioning.cattle.io/v1/cluster.go, pkg/generated/controllers/provisioning.cattle.io/v1/interface.go
Was running into this with the other PR - so will need to be merged for the new year.
=> [v0.5] `go generate` to update copyright year

charts/rancher-webhook/Chart.yaml
@tomleb noticed that the rancher-version was incorrect in the chart bump I created https://github.com/rancher/charts/pull/3340, this has to be updated first.
=> Update rancher version in chart

.drone.yml, pkg/generated/controllers/management.cattle.io/factory.go, pkg/generated/controllers/management.cattle.io/interface.go, pkg/generated/controllers/management.cattle.io/v3/cluster.go, pkg/generated/controllers/management.cattle.io/v3/clusterroletemplatebinding.go, pkg/generated/controllers/management.cattle.io/v3/globalrole.go, pkg/generated/controllers/management.cattle.io/v3/interface.go, pkg/generated/controllers/management.cattle.io/v3/node.go, pkg/generated/controllers/management.cattle.io/v3/podsecurityadmissionconfigurationtemplate.go, pkg/generated/controllers/management.cattle.io/v3/projectroletemplatebinding.go, pkg/generated/controllers/management.cattle.io/v3/roletemplate.go, pkg/generated/controllers/provisioning.cattle.io/factory.go, pkg/generated/controllers/provisioning.cattle.io/interface.go, pkg/generated/controllers/provisioning.cattle.io/v1/cluster.go, pkg/generated/controllers/provisioning.cattle.io/v1/interface.go
CI fails since we're no longer in 2023, so I just ran `go generate ./...`
Also cherry-pick the commit that removes the s390x runner.
=> [v0.3] Bump copyright year and remove s390x runner

pkg/auth/roleTemplate.go, pkg/auth/roleTemplate_test.go
The webhook doesn't allow user to grant inherited permissions to other users _in some cases_
Allow user to grant inherited permissions to other users
=> Grant inherited permissions to other users

docs.md, pkg/resources/common/validation.go, pkg/resources/common/validation_test.go, pkg/resources/management.cattle.io/v3/globalrole/GlobalRole.md, pkg/resources/management.cattle.io/v3/globalrole/validator.go, pkg/resources/management.cattle.io/v3/roletemplate/RoleTemplate.md, pkg/resources/management.cattle.io/v3/roletemplate/validator.go, tests/integration/globalRole_test.go, tests/integration/roleTemplate_test.go
See https://github.com/rancher/rancher/issues/40584
As described in the referenced issue, the roletemplate rules validation performs only a subset of the checks done by k8s on policy roles (besides the rancher-specific checks). In the referenced issue this is noted for `apiGroups`. The same problem would happen for the `resources`. The `verbs` field is ok, because this is checked explicitly.
The chosen solution calls on k8s functionality performing the entire set of rule checks for us.
The basic ability to do so was added with #309.
The core function for doing so, `validateRules`, is moved out of `globalrole` into the `common` package, to keep DRY.
As part of this unit tests were added. The tests pass.
After this refactor the `roletemplate` package is simply extended to call on this …
=> Fix roletemplate.rules validation, added standard k8s checks

Dockerfile.dapper, go.mod, go.sum
We've decided to bump 1.20 as part of supporting 1.27 in the v2.7 release.
It was done previously in the PR for v2.8: https://github.com/rancher/webhook/pull/287
The changes:
- Bump wrangler to a newer version (same as the one in v2.8)
- Bump go version in the Dapper container image and go.mod
=> Bump go 1.20

docs.md, pkg/resources/management.cattle.io/v3/project/Project.md, pkg/resources/management.cattle.io/v3/project/validator.go, pkg/resources/management.cattle.io/v3/project/validator_test.go
The Webhook doesn't validate container resource default limits that are associated with a new or updated Project. This results in controllers responsible for making the corresponding limit ranges in the project's namespaces to fail asynchronously. The K8s API server rejects limit ranges whose requests are greater than limits for any resource.
Add validation to Webhook on Project create and update.
=> Validate container default resource limit on projects

pkg/resources/management.cattle.io/v3/roletemplate/main_test.go, pkg/resources/management.cattle.io/v3/roletemplate/validator.go, pkg/resources/management.cattle.io/v3/roletemplate/validator_test.go
This should fix the integration tests in rancher/rancher issue that was introduced in https://github.com/rancher/webhook/pull/328 (see also https://github.com/rancher/rancher/issues/40584) which results in the following tests to fail:
```
test_default_roles.py::test_cluster_create_role_locked
test_default_roles.py::test_project_create_default_role
test_default_roles.py::test_project_create_role_locked
test_default_roles.py::test_user_create_default_role
```
The error looks like the following:
```
"rancher.cattle.io.roletemplates.management.cattle.io" denied the request: roletemplate.rules[8].nonResourceURLs: Invalid value: []string{"*"}: namespaced rules cannot apply to non-resource URLs\n\t{\'baseType\': \'error\', \'code\': \'BadRequest\', \'message\': \'admission webhook …
```
=> Validate RoleTemplate as non-namespaced

CODEOWNERS
The codeowner file references a group that was recently deleted and is no longer valid
Updated the codeowner to the new team name
=> Change codeowner to new team

CODEOWNERS
The codeowner file references a group that was recently deleted and is no longer valid
Updated the codeowner to the new team name
=> [v0.3] Change codeowners to new team

pkg/auth/roleTemplate.go, pkg/auth/roleTemplate_test.go
Reverts rancher/webhook#320. We're revisiting the way to fix this.
=> Revert "Grant inherited permissions to other users"

.golangci.json, Dockerfile.dapper, pkg/resolvers/aggregateResolver_test.go, pkg/resolvers/crtbResolver_test.go, pkg/resolvers/prtbResolver_test.go, tests/integration/rkeMachineConfig_test.go
Renovate bot is attempting to update `golangci-lint`, but in the newer version there are checks that fail. Specifically, it no longer allows variables in functions that go unused, instead requiring they be removed or set to `_`. Additionally, `run.skip-files` and `run.skip-dirs` are deprecated for `golangci-lint`.
Ran `golangci-lint` manually and fixed up all the errors. Used `issues.exclude-dirs` and `issues.exclude-files`, which are the newer, supported method of ignoring files/dirs.
=> [v0.4] Upgrade golangci-lint and fix warnings and errors associated with the new version

go.mod, go.sum
Few ACI fields couldn't be configured on Rancher v2.8.2 and v2.8.3 due to webhook not vendoring the latest RKE used by Rancher server versions. Updating RKE to the latest RC and will then bump it to v1.5.9 after RKE is released for Rancher v2.8.4. 
Issue: https://github.com/rancher/rancher/issues/44980
=> [v0.4] update rke to v1.5.9-rc2

pkg/auth/roleTemplate.go
webhook is automatically upgraded in Rancher 2.8.3. This is causing webhook to fail `RoleTemplate` evaluation because the feature flag doesn't exist.
act as if feature flag is disabled if it is not present.
=> Don't error if external-rules feature flag is not found when evaluating RoleTemplates

.drone.yml
Rancher v2.9-head image no longer contains zypper so we need another way to install Helm.
=> Fix integration test

README.md, docs.md, go.mod, go.sum, pkg/codegen/main.go, pkg/generated/objects/management.cattle.io/v3/objects.go, pkg/resources/management.cattle.io/v3/setting/Setting.md, pkg/resources/management.cattle.io/v3/setting/validator.go, pkg/resources/management.cattle.io/v3/setting/validator_test.go, pkg/resources/management.cattle.io/v3/userattribute/UserAttribute.md, pkg/resources/management.cattle.io/v3/userattribute/validator.go, pkg/resources/management.cattle.io/v3/userattribute/validator_test.go, pkg/server/handlers.go
Port of #390
* Validate user retention userattribute fields and settings
* [v0.4.s4] Don't allow empty lastLogin user attribute
=> [v0.5] s4: Fixes 227

pkg/auth/globalrole_test.go, pkg/auth/roleTemplate.go, pkg/auth/roleTemplate_test.go, pkg/clients/clients.go, pkg/resolvers/crtbResolver_test.go, pkg/resolvers/grbRuleResolvers_test.go, pkg/resolvers/prtbResolver_test.go, pkg/resources/management.cattle.io/v3/clusterroletemplatebinding/validator_test.go, pkg/resources/management.cattle.io/v3/feature/validator.go, pkg/resources/management.cattle.io/v3/feature/validator_test.go, pkg/resources/management.cattle.io/v3/globalrole/setup_test.go, pkg/resources/management.cattle.io/v3/globalrolebinding/validator_test.go, pkg/resources/management.cattle.io/v3/projectroletemplatebinding/validator_test.go, pkg/resources/management.cattle.io/v3/roletemplate/main_test.go, pkg/resources/management.cattle.io/v3/roletemplate/validator_test.go, pkg/server/handlers.go
`external-rules` feature flag was added in Rancher v2.7 and v2.8 to help admins with the transition of the new `RoleTemplate` field `ExternalRules`. That's no longer needed in Rancher v2.9
Remove `external-rules` feature flag. It will work as it is always enabled, and can't be disabled.
=> Remove external-rules feature flag

docs.md, go.mod, pkg/resources/provisioning.cattle.io/v1/cluster/Cluster.md, pkg/resources/provisioning.cattle.io/v1/cluster/mutator.go, pkg/resources/provisioning.cattle.io/v1/cluster/mutator_test.go
An issue was identified (https://github.com/rancher/rancher/issues/40609), where updating the node driver and changing the flags would result in CAPI detecting the supplied fields do not match the existing fields on the machine infrastructure custom resource. The fix for this issue was to persist the dynamicSchema onto the cluster object under the machinePools section, and stripping fields not present at the time of initial provisioning from the related CR, as the alternative of properly versioning CRDs for each node driver was not and continues to not be a viable solution. While this change initially fixed the issue of unintended cluster reprovisioning on node driver update, other cluster update solutions such as terraform and kubectl are still susceptible to this issue as an update …
=> Dynamic schema rfc

.github/workflows/ci.yaml
Technically not required for https://github.com/rancher/rancher/issues/45231 but related.
With flaky tests or Docker rate limit, it's very annoying to have a job's failure cancel another job. Instead, let all jobs run to completion, this way we can restart only the failed one.
=> Don't fail fast CI workflow

pkg/auth/roleTemplate.go
Forwardport of rancher/webhook#398 to the release/v0.4 line. 
For users running Rancher with an unpinned webhook version, rancher/rancher#46254 may occur.
N/A - see rancher/webhook#398.
=> Don't error if external-rules feature flag is not found

pkg/resources/management.cattle.io/v3/setting/validator.go, pkg/resources/management.cattle.io/v3/setting/validator_test.go, tests/integration/failPolicy_test.go
https://github.com/rancher/rancher/issues/45841
We have a "catch 22" situation with the settings validator as rancher may update some settings on startup while the webhook is starting up.
Change the `FailurePolicy` to `Ignore` on settings' validator to avoid timeouts.
=> [v0.5] Set FailurePolicy to Ignore for settings validator

.github/workflows/scripts/integration-test-ci, pkg/server/server.go, pkg/server/server_test.go, scripts/ci
https://github.com/rancher/rancher/issues/42611
A wrong variable is used when fetching the mutating webhook configuration, that may lead to the following errors on startup:
```
time="2024-07-18T14:01:43Z" level=error msg="Failed to ensure configuration: failed to create mutating configuration: MutatingWebhookConfiguration.admissionregistration.k8s.io \"\" is invalid: metadata.name: Required value: name or generateName is required"
time="2024-07-18T14:01:43Z" level=error msg="error syncing 'cattle-system/cattle-webhook-ca': handler secrets: failed to create mutating configuration: MutatingWebhookConfiguration.admissionregistration.k8s.io \"\" is invalid: metadata.name: Required value: name or generateName is required, requeuing"
```
Use the right/intended variable.
=> [v0.5] Use the proper config when fetching mutating webhook configuration

pkg/resources/management.cattle.io/v3/setting/validator.go, pkg/resources/management.cattle.io/v3/setting/validator_test.go
Verify that the actual value of the annotation is string "true" when checking that it's ok to change the tls-mode from `system-store` to `strict`.
Related to issue [#46189](https://github.com/rancher/rancher/issues/46189)
=> Stop testing the 'ok' part of a map access.

pkg/resources/management.cattle.io/v3/setting/validator.go, pkg/resources/management.cattle.io/v3/setting/validator_test.go
Issue - https://github.com/rancher/rancher/issues/46190
Verify that the actual value of the annotation is string "true" when checking that it's ok to change the tls-mode from `system-store` to `strict`.
Backport of #456 - see that PR for details.
=> [0.4] Stop testing the 'ok' part of a map access.

go.mod, go.sum
This updates both dependencies to their release tags, in prep for a webhook v0.5.1 release. The now unneeded replace directive for RKE was removed, see https://github.com/rancher/rancher/pull/43630 for context.
=> [v0.5] Update RKE to v1.6.0 and dynamiclistener to v0.6.0

go.mod, go.sum
This updates both dependencies to their release tags, in prep for a webhook v0.4.10 release.
=> [v0.4] Bump both rke and dymamiclistener to their release versions

docs.md, pkg/resources/provisioning.cattle.io/v1/cluster/Cluster.md, pkg/resources/provisioning.cattle.io/v1/cluster/validator.go, pkg/resources/provisioning.cattle.io/v1/cluster/validator_test.go
Data directories were not validated on creation. The should be validated based on the following criteria:
- Absolute paths (start with /)
- Clean (not contain env vars, shell expressions, ., or ..)
- Not set to the same path (no duplicates are allowed between any pairs of paths out of 3 configurable)
- Not nested one within another
Implement the above checks with the provisioning cluster validator
=> [46381] [2.10] Add validation to data directories on creation

charts/rancher-webhook/Chart.yaml
No related issue. Now that we're doing trunk-based development, the version in the trunk has to specify the version that current trunk work is targeting.
=> Current dev work is now for rancher 2.10

go.mod, go.sum
This is a forwardport of https://github.com/rancher/webhook/pull/475.
=> [Forwardport] Bump rke to v1.6.0 and dynamiclistener to v0.6.0

docs.md, pkg/resources/provisioning.cattle.io/v1/cluster/Cluster.md, pkg/resources/provisioning.cattle.io/v1/cluster/validator.go, pkg/resources/provisioning.cattle.io/v1/cluster/validator_test.go
Backport of https://github.com/rancher/webhook/pull/474
Data directories were not validated on creation. The should be validated based on the following criteria:
- Absolute paths (start with /)
- Clean (not contain env vars, shell expressions, ., or ..)
- Not set to the same path (no duplicates are allowed between any pairs of paths out of 3 configurable)
- Not nested one within another
Implement the above checks with the provisioning cluster validator
=> [46452] [2.9] validate data directories

go.mod, go.sum, pkg/server/server.go
Related to issue https://github.com/rancher/rancher/issues/46956 (v2.10)
This change displays any error messages and panic output from the dynamic listener's http server in rancher's log output
=> Display error output from dynamiclistener.Server

.github/workflows/scripts/start-rancher.sh
The deployment logic in r/r is a little complex for webhook.
Rancher has the rancher-webhook charts bundled in its image. Depending on timing and how well our git mirror is doing, Rancher might try to deploy the rancher-webhook chart embedded in the image, or it might deploy the chart pulled from the charts repo.
When it's pulling from the charts repo, then the webhook RC version in `CATTLE_RANCHER_WEBHOOK_VERSION` might be stale compared to the on in the charts repo. This leads to Rancher not being able to deploy webhook.
When using the bundled rancher-webhook chart, there's a very small chance that the bundled repo has a newer version of rancher-webhook than the one set in `CATTLE_RANCHER_WEBHOOK_VERSION`.
For the purpose of setting up Rancher for our tests, we really don't care what …
=> Fix webhook not deployed in CI

go.mod, go.sum, pkg/resources/management.cattle.io/v3/cluster/mutator.go, pkg/resources/management.cattle.io/v3/cluster/mutator_test.go
https://github.com/rancher/rancher/issues/47200
Presently mutating webhook drops fields not present in `Cluster` struct in RKE1. This creates problem for the users of ACI CNI provider.
We pass the marshaled `newCluster` object created by the function `ClusterOldAndNewFromRequest` instead of current approach of using `request.Object.Raw`.
This PR cherry-picks changes from @dharmit's https://github.com/rancher/webhook/pull/513 and adds tests as suggested in https://github.com/rancher/webhook/pull/513#pullrequestreview-2343698310. Also updated go.mod to add RKE in replace section per https://github.com/rancher/webhook/pull/513#issuecomment-2389665184.
=> Prevent dropping unknown cluster fields 

go.mod, pkg/resources/management.cattle.io/v3/cluster/mutator.go, pkg/resources/management.cattle.io/v3/cluster/mutator_test.go
Backport PR for https://github.com/rancher/webhook/pull/515. 
Issue: https://github.com/rancher/rancher/issues/47201
=> [v0.5] Prevent dropping unknown cluster fields 

go.mod, pkg/resources/management.cattle.io/v3/cluster/mutator.go, pkg/resources/management.cattle.io/v3/cluster/mutator_test.go
Backport PR for https://github.com/rancher/webhook/pull/515. 
Note: This PR uses `github.com/rancher/wrangler/v2/` vs the original PR uses `github.com/rancher/wrangler/v3/`. 
Issue: https://github.com/rancher/rancher/issues/47202
=> [v0.4] Prevent dropping unknown cluster fields

docs.md, pkg/auth/escalation.go, pkg/resources/common/common.go, pkg/resources/common/mutation.go, pkg/resources/common/mutation_test.go, pkg/resources/common/validation.go, pkg/resources/common/validation_test.go, pkg/resources/core/v1/secret/Secret.md, pkg/resources/core/v1/secret/mutator.go, pkg/resources/management.cattle.io/v3/cluster/Cluster.md, pkg/resources/management.cattle.io/v3/cluster/validator.go, pkg/resources/management.cattle.io/v3/cluster/validator_test.go, pkg/resources/management.cattle.io/v3/project/Project.md, pkg/resources/management.cattle.io/v3/project/validator.go, pkg/resources/management.cattle.io/v3/project/validator_test.go, pkg/resources/provisioning.cattle.io/v1/cluster/Cluster.md, pkg/resources/provisioning.cattle.io/v1/cluster/mutator.go, pkg/resources/rke-machine-config.cattle.io/v1/machineconfig/MachineConfig.md, pkg/resources/rke-machine-config.cattle.io/v1/machineconfig/mutator.go, tests/integration/provCluster_test.go, tests/integration/rkeMachineConfig_test.go, tests/integration/secret_test.go
Requires rancher/rancher changes: https://github.com/rancher/rancher/pull/47259
When a service account creates a cluster, the project handler and cluster handler both attempt to create ClusterOwner and ProjectOwner roles and bind those roles to the service account. The problem is that we don't support those roles for service accounts, so the logs get flooded with errors as it keeps retrying to add those roles.
To avoid the errors and the re-queuing, we have added a new annotation `field.cattle.io/no-creator-rbac`. When it is set the webhook does not set the `field.cattle.io/creatorId` annotation to clusters because the controllers will no longer be creating RBAC for the creator of the cluster.
I moved some annotations to the `common` package as I felt it was more apt. I also cleaned up …
=> Add checks for annotation to opt out of cluster owner RBAC

docs.md, pkg/codegen/docs.go, pkg/resources/cluster.cattle.io/v3/clusterauthtoken/ClusterAuthToken.md, pkg/resources/cluster.cattle.io/v3/clusterauthtoken/validator.go, pkg/resources/cluster.cattle.io/v3/clusterauthtoken/validator_test.go, pkg/resources/management.cattle.io/v3/token/Token.md, pkg/resources/management.cattle.io/v3/token/validator.go, pkg/resources/management.cattle.io/v3/token/validator_test.go, pkg/server/handlers.go
https://github.com/rancher/rancher/issues/45732
Related work
- https://github.com/rancher/rancher/pull/46313
- https://github.com/rancher/kube-api-auth/pull/28
A new optional field `lastUsedAt` was added to Token and ClusterAuthToken of type `metav1.Time`.
Validate that if set the `lastUsedAt` field of Token and ClusterAuthToken contains a valid RFC3339 date time value.
=> Validate LastUsedAt for Token and ClusterAuthToken

pkg/resources/cluster.cattle.io/v3/clusterauthtoken/validator.go
https://github.com/rancher/rancher/issues/45732
The `ClusterAuthToken` is a namespaced resource but the validator configuration had the `scope` set to `Cluster`. As a consequence the webhook hasn't been called on changes in ClusterAuthTokens.
Set the `scope` to `Namespaced` for `ClusterAuthToken`.
=> Use Namespaced scope for ClusterAuthToken validator

pkg/auth/roleTemplate.go
=> [v0.3] Don't error if external-rules feature flag is not found when evaluating RoleTemplates

pkg/resources/management.cattle.io/v3/project/mutator.go, pkg/resources/management.cattle.io/v3/project/mutator_test.go
Fixes an issue with https://github.com/rancher/webhook/pull/532 where the name wasn't being updated
=> [0.6] Make sure to update the name in the mutator

docs.md, pkg/resources/core/v1/namespace/Namespace.md, pkg/resources/core/v1/namespace/requestlimits.go, pkg/resources/core/v1/namespace/requestlimits_test.go, pkg/resources/core/v1/namespace/validator.go, pkg/resources/core/v1/namespace/validator_test.go
[#44825](https://github.com/rancher/rancher/issues/44825)
There is no validation of the cpu/memory request/limits when creating namespaces, which leads to Rancher attempting to create invalid objects.
The webhook now validates cpu/memory request/limits, if provided.
If a request or limit is provided by itself, we just validate that it is indeed a properly formatted value.
If both a cpu request/limit or a memory request/limit pair is provided, we also check to be sure that the request is less than or equal to the limit.
If parsing any of the provided values fails or if a request is greater than the limit, the webhook will refuse the request.
=> [main/2.10.2] Add resource request and limit validation when creating a namespace

.github/workflows/scripts/sync-deps.sh, .github/workflows/sync-deps.yaml
Automates syncing webhook and rancher dependencies. Simply go to actions tab, click on "Sync dependencies" workflow, click on "Run workflow", specify the webhook branch and the rancher branch and run.
The GHA workflow will compare the two dependency list (for specific dependencies) and will ensure webhook has the same. It will then create a PR and assign you to the PR. You can then review the PR.
Here's an example workflow run https://github.com/tomleb/rancher-webhook/actions/runs/12319259499 with its associated opened PR: https://github.com/tomleb/rancher-webhook/pull/19.
=> Add sync deps workflow

.github/workflows/scripts/sync-deps.sh, .github/workflows/sync-deps.yaml
Automates syncing webhook and rancher dependencies. Simply go to actions tab, click on "Sync dependencies" workflow, click on "Run workflow", specify the webhook branch and the rancher branch and run.
The GHA workflow will compare the two dependency list (for specific dependencies) and will ensure webhook has the same. It will then create a PR and assign you to the PR. You can then review the PR.
Here's an example workflow run https://github.com/tomleb/rancher-webhook/actions/runs/12319259499 with its associated opened PR: https://github.com/tomleb/rancher-webhook/pull/19.
=> [v0.6] Add sync deps workflow

.github/workflows/scripts/sync-deps.sh, .github/workflows/sync-deps.yaml
Automates syncing webhook and rancher dependencies. Simply go to actions tab, click on "Sync dependencies" workflow, click on "Run workflow", specify the webhook branch and the rancher branch and run.
The GHA workflow will compare the two dependency list (for specific dependencies) and will ensure webhook has the same. It will then create a PR and assign you to the PR. You can then review the PR.
Here's an example workflow run https://github.com/tomleb/rancher-webhook/actions/runs/12319259499 with its associated opened PR: https://github.com/tomleb/rancher-webhook/pull/19.
=> [v0.4] Add sync deps workflow

.github/workflows/scripts/sync-deps.sh, .github/workflows/sync-deps.yaml
Automates syncing webhook and rancher dependencies. Simply go to actions tab, click on "Sync dependencies" workflow, click on "Run workflow", specify the webhook branch and the rancher branch and run.
The GHA workflow will compare the two dependency list (for specific dependencies) and will ensure webhook has the same. It will then create a PR and assign you to the PR. You can then review the PR.
Here's an example workflow run https://github.com/tomleb/rancher-webhook/actions/runs/12319259499 with its associated opened PR: https://github.com/tomleb/rancher-webhook/pull/19.
=> [v0.5] Add sync deps workflow

.github/workflows/sync-deps.yaml
A PR created with a Github token from a GHA workflow run will not trigger the CI pull-request event so we end up with PR being opened but no CI running. Instead, let's use an app token. (https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/triggering-a-workflow#triggering-a-workflow-from-a-workflow)
=> Fix PR not triggering CI

tests/integration/clusterProxyConfig_test.go
=> Remove the race condition on the ClusterProxyConfig integration test (for release/v0.5)

.github/workflows/release-charts.yaml, .github/workflows/release-rancher.yaml, .github/workflows/scripts/release-against-charts.sh, .github/workflows/scripts/release-against-rancher.sh, .github/workflows/scripts/release-message.sh
This adds two workflows that can be triggered manually to bump webhook RCs to rancher/charts and rancher/rancher.
Creating a new release in rancher/charts and rancher/rancher will be simple:
1. Go to the rancher/webhook repo
2. Click on the `Actions` tab
3. On the left sidebar, click on the workflow that you want to run.
4. Enter the necessary input. Example in the image below.
5. Click `Run workflow`
This will do the following.
**charts**
Create a new branch off of the branch you input, make some changes to bump webhook, push to rancher/charts directly (more details below), create a pull request to the target branch. You can see an example here: https://github.com/rancher/charts/pull/4211.
**rancher**
Create a new branch off of the branch you input, update webhook version in build.yaml, …
=> Add workflow to release webhook in rancher/charts and rancher/rancher

.github/workflows/release-charts.yaml, .github/workflows/release-rancher.yaml
The path was wrong because we're in `charts` so the script should be `../webhook/....`
=> Fix release charts and release rancher GHA workflow again

.github/workflows/scripts/release-against-rancher.sh
Go telemetry in go 1.23 are written to `$HOME/.config/go/` (or xdg config). Rancher's dapper config points `$HOME` to the root of the repo, so running the `go generate`  command creates telemetry files which are then added with `git add .`. 
Since we don't want those files in the commit, we remove them before staging the files.
=> Ensure go telemetry files aren't added to the commit

pkg/resources/common/psa-validation.go, pkg/resources/core/v1/namespace/projectannotations.go, pkg/resources/core/v1/namespace/projectannotations_test.go, pkg/resources/core/v1/namespace/validator.go, pkg/resources/core/v1/namespace/validator_test.go, pkg/resources/management.cattle.io/v3/cluster/validator.go, pkg/resources/management.cattle.io/v3/cluster/validator_test.go, pkg/resources/provisioning.cattle.io/v1/cluster/validator.go
https://github.com/rancher/rancher/issues/32745
https://github.com/rancher/rancher/issues/48303
Presently, it's possible to delete the `local` cluster using:
```sh
$ k delete cluster.management.cattle.io local
```
Other ways the `local` cluster, one on which Rancher is deployed, could be corrupted are mentioned in https://github.com/rancher/rancher/issues/48303.
* Prevent `local` cluster deletion:
```sh
$  k delete cluster.management.cattle.io local
Error from server (BadRequest): admission webhook "rancher.cattle.io.clusters.management.cattle.io" denied the request: cannot delete the local cluster
```
* Prevent deletion of `local` and `fleet-local` namespaces:
```sh
$ k delete ns local
Error from server (BadRequest): admission webhook "rancher.cattle.io.namespaces" denied the request: …
```
=> Prevent deletion of `local` cluster

pkg/resources/management.cattle.io/v3/globalrolebinding/validator.go
When attempting to create a Global Role Binding when the Global Role doesn't exist, the error message looks like this:
```
apiVersion: management.cattle.io/v3
kind: GlobalRoleBinding
metadata:
name: test-grb1
globalRoleName: restricted-admin
userName: u-tdsgc
Error from server (BadRequest): error when creating "test.yaml": admission webhook "rancher.cattle.io.globalrolebindings.management.cattle.io" denied the request: globalrolebinding.globalRoleName: Not found: "test-grb1"
```
The error message was using the `GRB.Name` when it should be `GRB.GlobalRoleName`. Changed it.
=> Replace Name with GlobalRoleName in GlobalRoleBinding log

pkg/resources/core/v1/namespace/projectannotations.go, pkg/resources/core/v1/namespace/projectannotations_test.go
https://github.com/rancher/rancher/issues/47585
Webhook rejection message was not useful in this situation
Include user, verb, resource in the rejection message.
To make this situation show up, you can create a roletemplate like the one below
```
apiVersion: management.cattle.io/v3
builtin: false
context: project
description: ""
displayName: nomanagenamespace
external: false
hidden: false
kind: RoleTemplate
metadata:
generateName: rt-
rules:
- apiGroups:
- ""
resources:
- namespaces
verbs:
- '*'
- apiGroups:
- management.cattle.io
resources:
- projects
verbs:
- get
- list
- watch
- updatepsa
```
Then you can create a clusterroletemplatebinding to bind that role to a user that has no other permissions on a given cluster.
With that in place, login as the user to which the crtb was bound and …
=> [v0.7|main] Make admission rejection message more useful for namespace creation

pkg/resources/core/v1/namespace/projectannotations.go, pkg/resources/core/v1/namespace/projectannotations_test.go, pkg/resources/core/v1/namespace/validator.go, pkg/resources/core/v1/namespace/validator_test.go, pkg/resources/management.cattle.io/v3/cluster/validator.go, pkg/resources/management.cattle.io/v3/cluster/validator_test.go, pkg/resources/provisioning.cattle.io/v1/cluster/validator.go
* Prevent deletion of `local` cluster
It prevents deletion of both clusters.provisioning.cattle.io and cluster.management.cattle.io of the name `local`.
* Prevent deletion of `local` and `fleet-local` namespaces
* Parameter type grouping
---------
=> [release/v0.5] Prevent deletion of `local` cluster (#551)

go.mod, go.sum
https://github.com/rancher/rancher/issues/46908
=> [main] Change lasso with tagged release

docs.md, go.mod, pkg/resources/management.cattle.io/v3/cluster/Cluster.md, pkg/resources/management.cattle.io/v3/cluster/mutator.go, pkg/resources/management.cattle.io/v3/cluster/mutator_test.go, pkg/resources/management.cattle.io/v3/cluster/validator.go, pkg/resources/management.cattle.io/v3/cluster/validator_test.go, pkg/server/handlers.go
https://github.com/rancher/rancher/issues/41010
As a new feature, Rancher will allow enabling or disabling version management for imported RKE2/K3s clusters. 
A new annotation on the management v3 cluster object will be used to control the cluster-level setting. 
Rancher Webhook will ensure that the annotation is correctly set on eligible clusters.
Please refer to the RFC for design details. 
Please refer to the RFC for design details.  
Alternatively, the changes are outlined in the `pkg/resources/management.cattle.io/v3/cluster/Cluster.md` file. 
This PR was also validated by running the binary and pointing it to a Rancher setup.
=> Support for Version Management on Imported RKE2/K3s Clusters

docs.md, pkg/resources/management.cattle.io/v3/setting/Setting.md, pkg/resources/management.cattle.io/v3/setting/validator.go, pkg/resources/management.cattle.io/v3/setting/validator_test.go
This depends on: https://github.com/rancher/rancher/pull/48778 to be merged and refers to the following RFC: https://docs.google.com/document/d/1jN2faXl9FEb2E_9Ohm7uBrrVwuwnIj4HORiL4Wb9Udw/edit?tab=t.0
This PR adds validation functionality to the webhook, for a new user attribute: `auth-user-session-idle-ttl-minutes`.
This parameter differs from the existing `auth-user-session-ttl-minutes` as the former tracks UI activity such as mouse clicks and keystrokes, while the latter is a timer for user session.
Rancher has `auth-user-session-ttl-minutes` to set a max length a UI session (16hrs) can last, where has user is idle for a specific time and come back still session is valid now. i.e., There is no configurable parameter to set the idle session timeout.
For rancher/webhook I developed the …
=> feat(setting): add validation for auth-user-session-idle-ttl-minutes

pkg/resources/core/v1/namespace/deleteNamespace.go, pkg/resources/core/v1/namespace/deleteNamespace_test.go, pkg/resources/core/v1/namespace/projectannotations.go, pkg/resources/core/v1/namespace/psalabels.go, pkg/resources/core/v1/namespace/requestlimits.go, pkg/resources/core/v1/namespace/validator.go, pkg/resources/core/v1/namespace/validator_test.go, pkg/resources/management.cattle.io/v3/cluster/validator.go, pkg/resources/management.cattle.io/v3/cluster/validator_test.go, pkg/resources/provisioning.cattle.io/v1/cluster/validator.go
https://github.com/rancher/rancher/issues/32745
https://github.com/rancher/rancher/issues/48303
* Presently, it's possible to delete `local` cluster (both kinds `clusters.provisioning.cattle.io` and `cluster.management.cattle.io`) using `kubectl delete` commands.
* Presently, it's possible to delete `local` and `fleet-local` namespaces using `kubectl delete`.
All aforementioned deletions can be prevented using the proposed PR.
```sh
$ k delete clusters.provisioning.cattle.io -n fleet-local local
Error from server (BadRequest): admission webhook "rancher.cattle.io.clusters.provisioning.cattle.io" denied the request: can't delete local cluster
$ k delete cluster.management.cattle.io local
Error from server (BadRequest): admission webhook "rancher.cattle.io.clusters.management.cattle.io" …
```
=> Prevent deletion of namespaces and cluster

pkg/resources/management.cattle.io/v3/setting/validator.go, pkg/resources/management.cattle.io/v3/setting/validator_test.go
When the backup restore operator attempts to restore a snapshot taken from a rancher version including the PC and PDB feature, the webhook will attempt to validate the `cluster-agent-default-priority-class` and `cluster-agent-default-pod-disruption-budget` settings even if they have not been customized. This results in a json marshaling error, blocking the request. This issue will only reproduce when attempting to reapply the default settings json through BRO or manually. Manual reproduction steps can be found in the linked BRO issue. 
Add a conditional to ensure that the setting is only validated if it has been customized. 
- No documentation updates required
=> Do not validate PC and PDB settings if they have not been customized

pkg/resources/core/v1/namespace/deleteNamespace.go, pkg/resources/core/v1/namespace/deleteNamespace_test.go, pkg/resources/core/v1/namespace/projectannotations.go, pkg/resources/core/v1/namespace/psalabels.go, pkg/resources/core/v1/namespace/validator.go, pkg/resources/core/v1/namespace/validator_test.go, pkg/resources/management.cattle.io/v3/cluster/validator.go, pkg/resources/management.cattle.io/v3/cluster/validator_test.go, pkg/resources/provisioning.cattle.io/v1/cluster/validator.go
Backport of #651 
* Ignore namespace delete operation
* Prevent deletion of `local` and `fleet-local` namespaces
* Prevent deletion of local cluster
It prevents deletion of both clusters.provisioning.cattle.io and cluster.management.cattle.io resources of the named local.
* Fixes to tests based on CI feedback
---------
Fixes: https://github.com/rancher/rancher/issues/48304
=> [release/v0.6] Prevent deletion of namespaces and cluster #651

pkg/resources/core/v1/namespace/deleteNamespace.go, pkg/resources/core/v1/namespace/deleteNamespace_test.go, pkg/resources/core/v1/namespace/projectannotations.go, pkg/resources/core/v1/namespace/psalabels.go, pkg/resources/core/v1/namespace/validator.go, pkg/resources/core/v1/namespace/validator_test.go, pkg/resources/management.cattle.io/v3/cluster/validator.go, pkg/resources/management.cattle.io/v3/cluster/validator_test.go, pkg/resources/provisioning.cattle.io/v1/cluster/validator.go
* Ignore namespace delete operation
* Prevent deletion of `local` and `fleet-local` namespaces
* Prevent deletion of local cluster
It prevents deletion of both clusters.provisioning.cattle.io and cluster.management.cattle.io resources of the named local.
* Fixes to tests based on CI feedback
---------
Fixes: https://github.com/rancher/rancher/issues/48305
=> [release/v0.5] Prevent deletion of namespaces and cluster (#651)

go.mod, pkg/codegen/docs.go, pkg/resources/provisioning.cattle.io/v1/cluster/mutator.go
Issue https://github.com/rancher/webhook/issues/677
golang.org/x/exp/slices uses `slices` indirectly 😄
=> Remove usage of golang.org/x/exp

charts/rancher-webhook/Chart.yaml
Upgrading rancher-version to 2.11 was missed in the 1.32 upgrade PR #672
=> [release/v0.7] Upgrade charts rancher-version to 2.11

go.mod, go.sum
=> [release/v0.7] bump dynamiclistever version

README.md
There's no issue for this PR
Currently there's only one way to test the webhook development.
This PR introduces an alternative way to test it by importing the built image into the cluster and patching the webhook deployment.
Credits to @raulcabello and @JonCrowther for suggestion.
=> docs: add alternative method to test webhook development

.github/workflows/release-charts.yaml, .github/workflows/release-rancher.yaml
**Backport**
Backport of https://github.com/rancher/webhook/pull/851
You can make changes to this PR with the following command:
```
git clone https://github.com/rancher/webhook
cd webhook
git switch backport-851-release-v0.7-21702
```
---
If a PR is made to bump webhook in rancher/rancher but that version is not yet in rancher/charts, then the CI will be very broken (unless quite lucky). Here's why.
The CI in rancher/rancher runs the `build-server` job which builds the docker images and [publishes them as artifact](https://github.com/rancher/rancher/blob/969647581012ad8bd695b7f673534e1be5200c11/.github/workflows/pull-request.yml#L120-L127). 
Then, the `test` (for integration test) job [downloads those same artifacts](https://github.com/rancher/rancher/blob/969647581012ad8bd695b7f673534e1b …
=> [release/v0.7] Prevent creating Rancher PR if RC not yet in rancher/charts

.github/workflows/release-charts.yaml, .github/workflows/release-rancher.yaml, .github/workflows/scripts/release-against-charts.sh, .github/workflows/scripts/release-against-rancher.sh, .github/workflows/scripts/release-message.sh
We're going to do the same as the Sync dependencies GHA workflow and add it to every supported branch because we want:
- per-branch specific behavior (eg: some needs to remove the RC, some don't)
- consistency between these and the sync deps
Nothing changed in the scripts except the default values.
=> [v0.4] Migrate release GHA to be per branch

.github/workflows/release-charts.yaml, .github/workflows/release-rancher.yaml, .github/workflows/scripts/release-against-charts.sh, .github/workflows/scripts/release-against-rancher.sh, .github/workflows/scripts/release-message.sh
We're going to do the same as the Sync dependencies GHA workflow and add it to every supported branch because we want:
- per-branch specific behavior (eg: some needs to remove the RC, some don't)
- consistency between these and the sync deps
Nothing changed in the scripts except the default values.
=> [v0.5] Migrate release GHA to be per branch

Dockerfile.dapper, go.mod
Go was bumped to 1.24 for rancher/rancher main and #869 requires updating rancher/rancher/pkg/apis.
The latest stable BCI image contains Go 1.24.2.
```sh
docker inspect registry.suse.com/bci/golang:1.24 | grep GOLANG_VERSION
"GOLANG_VERSION=1.24.2",
```
Bump Go to v1.24.2.
=> Bump Go to 1.24.2

.github/workflows/scripts/release-against-charts.sh
Backport of https://github.com/rancher/webhook/pull/868
Charts should now support multiple RCs so we no longer need to delete old RCs. This will prevent breaking the CI whenever we bump webhook for example (or worse when both webhook and fleet are bumped at the same time).
=> [v0.6] Don't remove previous RCs

pkg/resources/management.cattle.io/v3/project/mutator.go
Follow up of https://github.com/rancher/webhook/pull/869
That change generates the name and creates a namespace for it, but it didn't update the name of the project, so the name would then be generated by the kubernetes controller resulting in a different named namespace and project.
This fixes it.
=> Make sure to update the project with the generated name

.github/workflows/release-charts.yaml
Update release-charts action to use the new dev-v2.12 branch of charts by default
=> Update default chart branch to dev-v2.12

pkg/resources/core/v1/namespace/psalabels.go, pkg/resources/core/v1/namespace/psalabels_test.go
Currently, updatepsa is only available to Cluster Roles and not Project Roles due to security concern. Customer wants the ability to assign this to a Project Role.
Allow user to update PSA when admin grant access to do it.
In this PR, we are adding information to craft a better SAR (SubjectAccessReview) request.
=> feat: updatepsa for project level

pkg/resources/provisioning.cattle.io/v1/cluster/mutator.go, pkg/resources/provisioning.cattle.io/v1/cluster/mutator_test.go, pkg/resources/provisioning.cattle.io/v1/cluster/validator.go
Currently, the `getKubeAPIServerArgs` logic parses the key-value args into a `map[string]string`. As a result any modification to the current map followed by a call to `setKubeAPIServerArgs` alters the original orde of arguments in cluster's `machineGlobalConfig["kube-apiserver-arg"]`.
This change in the sequence of elements is expected given the usage of maps, but leads to severe issues with Terraform.
Instead of parsing the arguments into `map[string]string`, this commit parses the arguments into a slice of struct {key, value string}. 
This change preserves the original ordering of arguments as defined in the cluster's `machineGlobalConfig`, ensuring compatibility with tools like Terraform that are sensitive to input order.
=> Preserves the original sequence of machineConfigGlobal["kube-apiserver-arg"]

pkg/resources/provisioning.cattle.io/v1/cluster/mutator.go, pkg/resources/provisioning.cattle.io/v1/cluster/mutator_test.go, pkg/resources/provisioning.cattle.io/v1/cluster/validator.go
Backport of https://github.com/rancher/webhook/pull/913
Currently, the `getKubeAPIServerArgs` logic parses the key-value args into a `map[string]string`. As a result any modification to the current map followed by a call to `setKubeAPIServerArgs` alters the original order of arguments in cluster's `machineGlobalConfig["kube-apiserver-arg"]`.
This change in the sequence of elements is expected given the usage of maps, but leads to severe issues with Terraform.
Instead of parsing the arguments into `map[string]string`, this commit parses the arguments into a slice of struct {key, value string}.
This change preserves the original ordering of arguments as defined in the cluster's `machineGlobalConfig`, ensuring compatibility with tools like Terraform that are sensitive to input order.
=> [backport v2.11] Preserves the original sequence of machineConfigGlobal["kube-apiserver-arg"]

pkg/resources/provisioning.cattle.io/v1/cluster/mutator.go, pkg/resources/provisioning.cattle.io/v1/cluster/mutator_test.go, pkg/resources/provisioning.cattle.io/v1/cluster/validator.go
Backport of https://github.com/rancher/webhook/pull/913
Currently, the `getKubeAPIServerArgs` logic parses the key-value args into a `map[string]string`. As a result any modification to the current map followed by a call to `setKubeAPIServerArgs` alters the original order of arguments in cluster’s `machineGlobalConfig[“kube-apiserver-arg”]`.
This change in the sequence of elements is expected given the usage of maps, but leads to severe issues with Terraform.
Instead of parsing the arguments into `map[string]string`, this commit parses the arguments into a slice of struct {key, value string}.
This change preserves the original ordering of arguments as defined in the cluster’s `machineGlobalConfig`, ensuring compatibility with tools like Terraform that are sensitive to input order.
=> [backport v2.10] Preserves the original sequence of machineConfigGlobal["kube-apiserver-arg"]

docs.md, pkg/resources/management.cattle.io/v3/authconfig/Authconfig.md, pkg/resources/management.cattle.io/v3/authconfig/validator.go, pkg/resources/management.cattle.io/v3/authconfig/validator_test.go
https://github.com/rancher/rancher/issues/50470
In #682 we made the certificate required for LDAP/AD auth providers if the TLS is set to on, but it's only required for self-signed certs.
Don't require the certificate if the TLS is on for LDAP/AD auth providers.
=> Don't require certificate if tls is on for ldap/ad authconfigs

pkg/resources/provisioning.cattle.io/v1/cluster/mutator.go, pkg/resources/provisioning.cattle.io/v1/cluster/mutator_test.go, pkg/resources/provisioning.cattle.io/v1/cluster/validator.go
Follow up to https://github.com/rancher/webhook/pull/926
Backport of #928 
This PR:
- Decouples `parseFromRawArgs` from the keyValueArgs receiver.
- Simplifies the logic and results in improved performance.
- Updates `getKubeAPIServerArgs` to return errors to the UI.
Per benchmark, this approach improves the performance by ~10-12%.
=> [backport v2.10] Refactors keyValueArgs handling for improved efficiency (#928)

go.mod
Our pinning of rke was accidentally removed.  This restores it.
Pinned to version nearest to r/r that is in an un-rc state.
=> Restore pinning of github.com/rancher/rke to un-rc version

docs.md, pkg/resources/management.cattle.io/v3/users/User.md, pkg/resources/management.cattle.io/v3/users/validator.go, pkg/resources/management.cattle.io/v3/users/validator_test.go
UserName was immutable in Norman, but with public API we need a webhook to do that validation.
Added a new validation. It's possible to add a UserName if none existed, but not to change an existing one.
=> Add update validation for User.UserName

docs.md, pkg/resources/management.cattle.io/v3/users/User.md, pkg/resources/management.cattle.io/v3/users/validator.go, pkg/resources/management.cattle.io/v3/users/validator_test.go
Reverts the changes from this PR https://github.com/rancher/webhook/pull/943 in the v0.8 branch. I meant for it to only go into `main`, but didn't realize we hadn't branched off the v2.12 versions yet.
=> [v0.8] Revert user update validation changes

pkg/resources/management.cattle.io/v3/cluster/validator.go, pkg/resources/management.cattle.io/v3/cluster/validator_test.go
Backport from https://github.com/rancher/webhook/pull/990
https://github.com/rancher/rancher/issues/51024
Described on issue. TLDR: the warning is not useful anymore.
=> [Backport v0.8] Fix removing imported warning

pkg/resources/provisioning.cattle.io/v1/cluster/mutator.go, pkg/resources/provisioning.cattle.io/v1/cluster/mutator_test.go
Issue: https://github.com/rancher/backup-restore-operator/issues/663
=> [release/v0.8] Label admission-configuration-psact secret to be backed up

docs.md, pkg/resources/provisioning.cattle.io/v1/cluster/Cluster.md, pkg/resources/provisioning.cattle.io/v1/cluster/validator.go, pkg/resources/provisioning.cattle.io/v1/cluster/validator_test.go
https://github.com/rancher/rancher/issues/50987
While creating a node driver or custom RKE2/k3s cluster, if the secret used for saving etcd backups to S3 does not exist, then the cluster will be stuck waiting for node ref, and Rnacher will generate empty plans for nodes.
Note that this bug can only be triggered when creating or updating the cluster programmatically or via editing YAML.
Add validation for the etcd S3 cloud credential to reject the request for creating or updating the provisioning cluster if the provided secret does not exist.
=> [2.13] add validation for etcd s3 cloud credential 

docs.md, pkg/resources/management.cattle.io/v3/users/User.md, pkg/resources/management.cattle.io/v3/users/validator.go, pkg/resources/management.cattle.io/v3/users/validator_test.go, pkg/server/handlers.go
Backport of https://github.com/rancher/webhook/pull/1053 with some additional code pulled from https://github.com/rancher/webhook/pull/1015
The original backport https://github.com/rancher/webhook/pull/1053 has the username uniqueness check on update, and https://github.com/rancher/webhook/pull/1015 has the check on create.
=> [v0.7] Username uniqueness check for Create and Update

docs.md, pkg/resources/provisioning.cattle.io/v1/cluster/Cluster.md, pkg/resources/provisioning.cattle.io/v1/cluster/validator.go, pkg/resources/provisioning.cattle.io/v1/cluster/validator_test.go
https://github.com/rancher/webhook/pull/410 introduced data directory validation to the webhook, designed to prevent users from changing data directories once the cluster has been created. Harvester leverages rancherd, which is effectively a self-bootstrapping mechanism for creating the Rancher local cluster. Part of this bootstrapping involves patching the local cluster to set the rkeConfig: {}, which result in Rancher reconciling it like any other normal CAPI cluster.
Previously, the webhook did not come up quick enough in the rancherd process, but now the webhook and it's related validatingwebhookconfiguration exists before the cluster can be patched. The data directory validation causes the webhook to panic (and reject the request), as it was not expected that a cluster would go from …
=> Fix crash when rancherd patches local cluster

pkg/resources/provisioning.cattle.io/v1/cluster/mutator.go, pkg/resources/provisioning.cattle.io/v1/cluster/mutator_test.go, pkg/resources/provisioning.cattle.io/v1/cluster/validator.go
Per the changes introduces with https://github.com/rancher/webhook/pull/913, the `kube-apiserver-arg` are deduplicated. This causes issues for k8s-specific flags that are allowed to be specified multiple times.
This commit instead of maintaining a `keyValueArg{}` struct:
- Parses the arguments as a `[]string`.
- Deletes/Prepends the `kubeAPIAdmissionConfigOption` key-value pair as per the condition.
- Sets the arguments back as is (ensuring no modification to the user-specified args).
=> Preserves kube-apiserver-arg, webhook prepends PSACT mount path if needed

pkg/resources/provisioning.cattle.io/v1/cluster/mutator.go, pkg/resources/provisioning.cattle.io/v1/cluster/mutator_test.go, pkg/resources/provisioning.cattle.io/v1/cluster/validator.go
Backport of: #1096
Per the changes introduces with https://github.com/rancher/webhook/pull/913, the kube-apiserver-arg are deduplicated. This causes issues for k8s-specific flags that are allowed to be specified multiple times.
This commit instead of maintaining a keyValueArg{} struct:
- Parses the arguments as a []string.
- Deletes/Prepends the kubeAPIAdmissionConfigOption key-value pair as per the condition.
- Sets the arguments back as is (ensuring no modification to the user-specified args).
=> [backport v2.11] Preserves kube-apiserver-arg, webhook prepends PSACT mount path if needed

pkg/resources/provisioning.cattle.io/v1/cluster/mutator.go, pkg/resources/provisioning.cattle.io/v1/cluster/mutator_test.go, pkg/resources/provisioning.cattle.io/v1/cluster/validator.go
Backport of: #1096
Per the changes introduces with https://github.com/rancher/webhook/pull/913, the kube-apiserver-arg are deduplicated. This causes issues for k8s-specific flags that are allowed to be specified multiple times.
This commit instead of maintaining a keyValueArg{} struct:
- Parses the arguments as a []string.
- Deletes/Prepends the kubeAPIAdmissionConfigOption key-value pair as per the condition.
- Sets the arguments back as is (ensuring no modification to the user-specified args).
=> [backport v2.12] Preserves kube-apiserver-arg, webhook prepends PSACT mount path if needed

pkg/resources/management.cattle.io/v3/users/validator.go, pkg/resources/management.cattle.io/v3/users/validator_test.go
Admin can deactivate itself.
- `request.UserInfo.Username` contains the `user.Name` not the `user.Username`, which is not always the same
- `Enabled` defaults to true if not initialized
=> Fix admin can deactivate itself
